
-- Create dilekce_templates table
CREATE TABLE IF NOT EXISTS public.dilekce_templates (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    category TEXT NOT NULL,
    title TEXT NOT NULL,
    url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.dilekce_templates ENABLE ROW LEVEL SECURITY;

-- Allow read access to authenticated users
CREATE POLICY "Allow read access for authenticated users on dilekce_templates" 
ON public.dilekce_templates FOR SELECT 
TO authenticated 
USING (true);

-- Optional: Allow anon read if needed
CREATE POLICY "Allow read access for anon on dilekce_templates" 
ON public.dilekce_templates FOR SELECT 
TO anon 
USING (true);

-- Insert templates
INSERT INTO public.dilekce_templates (category, title, url) VALUES
('Aile ve Boşanma Hukuku', '6284 Koruma Kararı Talebi Dilekçesi Örneği (2026) ve İhlal Bildirimi', 'https://hukukcularevi.com/6284-koruma-karari-talebi-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', '6284 Tedbir Kararına İtiraz Dilekçesi Örneği (2026) — 2 Haftalık Süre', 'https://hukukcularevi.com/6284-tedbir-kararina-itiraz-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Adli Yardım Talebi Dilekçesi Örneği (2026) — HMK 334', 'https://hukukcularevi.com/adli-yardim-talebi-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Aile Hukuku Örnek Dilekçeler (2026) — Boşanma, Nafaka, Velayet', 'https://hukukcularevi.com/aile-hukuku-ornek-dilekceler/'),
('Aile ve Boşanma Hukuku', 'Aile Konutu Tapu İptali ve Tescil Dilekçesi Örneği (2026) — TMK 194', 'https://hukukcularevi.com/aile-konutu-tapu-iptali-tescil-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Aile Konutu Şerhi Talep Dilekçesi Örneği (2026) — TMK 194', 'https://hukukcularevi.com/aile-konutu-serhi-talebi-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Ayrılık Davası Dilekçesi Örneği (2026) — TMK 167-172', 'https://hukukcularevi.com/ayrilik-davasi-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Babalık Davası Dilekçesi Örneği (2026) — TMK 301-304', 'https://hukukcularevi.com/babalik-davasi-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Boşanma Dava Dilekçesi Örneği (2026) — Çekişmeli Boşanma', 'https://hukukcularevi.com/bosanma-dava-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Boşanma Davasına Cevap Dilekçesi Örneği (2026) — 2 Hafta', 'https://hukukcularevi.com/bosanma-cevap-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Boşanmada Maddi ve Manevi Tazminat Talebi Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/bosanmada-tazminat-talebi-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Boşanmada İstinaf Dilekçesi Nasıl Yazılır? Süre ve Usul', 'https://hukukcularevi.com/bosanmada-istinaf-dilekcesi-nasil-yazilir/'),
('Aile ve Boşanma Hukuku', 'Evlat Edinme Talebi Dilekçesi Örneği (2026) — TMK 305-315', 'https://hukukcularevi.com/evlat-edinme-talebi-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Kayyım Atanması Talebi Dilekçesi Örneği (2026) — TMK 426', 'https://hukukcularevi.com/kayyim-atanmasi-talebi-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Mal Paylaşımı (Mal Rejimi Tasfiyesi) Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/mal-paylasimi-dava-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Nafaka Artırım Dilekçesi Örneği (2026) — TMK 176/4', 'https://hukukcularevi.com/nafaka-artirim-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Nafaka Azaltma / Kaldırma Dilekçesi Örneği (2026) — TMK 176', 'https://hukukcularevi.com/nafaka-azaltma-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Nüfus Kaydı Düzeltme Dilekçesi Örneği (2026) — Yaş ve Kayıt Hatası', 'https://hukukcularevi.com/nufus-kaydi-duzeltme-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Soybağının Reddi Davası Dilekçesi Örneği (2026) — TMK 286-289', 'https://hukukcularevi.com/soybaginin-reddi-davasi-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Tanıma Beyanı Dilekçesi Örneği (2026) — TMK 295', 'https://hukukcularevi.com/tanima-beyani-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Tedbir Nafakası Talep Dilekçesi Örneği (2026) — TMK 169', 'https://hukukcularevi.com/tedbir-nafakasi-talep-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Vasi Atanması (Kısıtlama) Talebi Dilekçesi Örneği (2026) — TMK 405', 'https://hukukcularevi.com/vasi-atanmasi-talebi-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Velayet Değişikliği Dilekçesi Örneği (2026) — TMK 183', 'https://hukukcularevi.com/velayet-degisikligi-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Vesayetin (Vasiliğin) Kaldırılması Talebi Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/vesayetin-kaldirilmasi-talebi-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Yabancı Boşanma Kararının Tanınması Dilekçesi Örneği (2026) — MÖHUK 50', 'https://hukukcularevi.com/yabanci-bosanma-kararinin-taninmasi-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Yardım Nafakası Davası Dilekçesi Örneği (2026) — TMK 364', 'https://hukukcularevi.com/yardim-nafakasi-davasi-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Ziynet Alacağı Davası Dilekçesi Örneği (2026) — TMK 220', 'https://hukukcularevi.com/ziynet-alacagi-davasi-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Çocukla Kişisel İlişki Dilekçesi Örneği (2026) — ADM Başvurusu', 'https://hukukcularevi.com/cocukla-kisisel-iliski-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'İddet Müddetinin Kaldırılması Dilekçesi Örneği (2026) — TMK 132', 'https://hukukcularevi.com/iddet-muddetinin-kaldirilmasi-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'İsim ve Soyisim Değişikliği Davası Dilekçesi Örneği (2026) — TMK 27', 'https://hukukcularevi.com/isim-soyisim-degisikligi-davasi-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Anlaşmalı Boşanma Dava Dilekçesi Örneği (2026) — TMK m.166/3', 'https://hukukcularevi.com/anlasmali-bosanma-dava-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'Anlaşmalı Boşanma Protokolü Örneği (2026) — Madde Madde Hazır Metin', 'https://hukukcularevi.com/anlasmali-bosanma-protokolu-ornegi-2026/'),
('Aile ve Boşanma Hukuku', 'Velayetin Değiştirilmesi Dava Dilekçesi Örneği (2026) — TMK m.183 ve Üstün Yarar', 'https://hukukcularevi.com/velayetin-degistirilmesi-dava-dilekcesi-ornegi-tmk-183/'),
('Aile ve Boşanma Hukuku', 'Çocuğun Pasaportu ve Yurt Dışı İzni Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/cocugun-pasaportu-ve-yurt-disi-izni-dava-dilekcesi-ornegi/'),
('Aile ve Boşanma Hukuku', 'fon mağduru dilekçe örnekleri dizininde', 'https://hukukcularevi.com/fon-magduru-dilekce-ihtarname-ornekleri-dizin-bilgi-talebi-tasfiye-bankasi-spk-sikayet-savcilik-dava-2026/'),
('İcra ve İflas Hukuku', 'Emekli Maaşı Haczine İtiraz (Şikâyet) Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/emekli-maasi-haczine-itiraz-dilekcesi-ornegi/'),
('İcra ve İflas Hukuku', 'Haczin Kaldırılması (Fek) Talebi Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/haczin-kaldirilmasi-fek-talebi-dilekcesi-ornegi/'),
('İcra ve İflas Hukuku', 'Haricen Tahsil Bildirim Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/haricen-tahsil-bildirim-dilekcesi-ornegi/'),
('İcra ve İflas Hukuku', 'Kambiyo Senedine İtiraz Dilekçesi Örneği (2026) — 5 Gün', 'https://hukukcularevi.com/kambiyo-senedine-itiraz-dilekcesi-ornegi/'),
('İcra ve İflas Hukuku', 'Mal Beyanı Dilekçesi Nasıl Yazılır? Örnek ve İpuçları', 'https://hukukcularevi.com/mal-beyaninda-bulunma-yukumlulugu/'),
('İcra ve İflas Hukuku', 'Mal Beyanı Dilekçesi Örneği ve Doldurma Rehberi', 'https://hukukcularevi.com/mal-beyani-dilekcesi-ornegi/'),
('İcra ve İflas Hukuku', 'Menfi Tespit Dava Dilekçesi Örneği (2026) — İİK 72', 'https://hukukcularevi.com/menfi-tespit-dava-dilekcesi-ornegi/'),
('İcra ve İflas Hukuku', 'Meskeniyet (Haline Münasip Ev) Şikâyet Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/meskeniyet-iddiasi-sikayet-dilekcesi-ornegi/'),
('İcra ve İflas Hukuku', 'İcra Hukuku Örnek Dilekçeler ve Şablonlar (2026)', 'https://hukukcularevi.com/icra-hukuku-ornek-dilekceler/'),
('İcra ve İflas Hukuku', 'İcra Takibine İtiraz Dilekçesi Örneği (2026) — 7 Gün', 'https://hukukcularevi.com/icra-takibine-itiraz-dilekcesi-ornegi/'),
('İcra ve İflas Hukuku', 'İcra Taksitlendirme (Taksitle Ödeme) Talebi Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/icra-taksitlendirme-talebi-dilekcesi-ornegi/'),
('İcra ve İflas Hukuku', 'İtirazın İptali Dava Dilekçesi Örneği (2026) — İİK 67', 'https://hukukcularevi.com/itirazin-iptali-dava-dilekcesi-ornegi/'),
('İcra ve İflas Hukuku', 'İhtiyati Haciz Talebi Dilekçesi Örneği (2026) — İİK m.257 ve 10+7 Gün Kuralı', 'https://hukukcularevi.com/ihtiyati-haciz-talebi-dilekcesi-ornegi/'),
('İcra ve İflas Hukuku', 'İstihkak Dava Dilekçesi Örneği (2026) — İİK m.96-99 ve 7 Gün', 'https://hukukcularevi.com/istihkak-dava-dilekcesi-ornegi-iik-96-99/'),
('İcra ve İflas Hukuku', 'İhalenin Feshi Dilekçesi Örneği (2026) — İİK m.134, 7 Gün ve %10 Risk', 'https://hukukcularevi.com/ihalenin-feshi-dilekcesi-ornegi-iik-134/'),
('İcra ve İflas Hukuku', 'Tasarrufun İptali Dava Dilekçesi Örneği (2026) — 7571 Sonrası İİK m.277-284', 'https://hukukcularevi.com/tasarrufun-iptali-dava-dilekcesi-ornegi-iik-277/'),
('İcra ve İflas Hukuku', 'Sıra Cetveline İtiraz Dilekçesi Örneği (2026) — İİK m.142 ve 7 Gün', 'https://hukukcularevi.com/sira-cetveline-itiraz-dava-dilekcesi-ornegi-iik-142/'),
('İcra ve İflas Hukuku', 'Karşılıksız Çek Şikâyet Dilekçesi Örneği (2026) — 5941 m.5 ve İcra Ceza', 'https://hukukcularevi.com/karsiliksiz-cek-sikayet-dilekcesi-ornegi-5941/'),
('İcra ve İflas Hukuku', 'Nafaka Ödememe Şikâyet Dilekçesi Örneği (2026) — İİK m.344 ve Tazyik Hapsi', 'https://hukukcularevi.com/nafaka-odememe-sikayet-dilekcesi-ornegi-iik-344/'),
('İcra ve İflas Hukuku', 'İtirazın Kaldırılması Dilekçesi Örneği (2026) — İİK m.68 ve 6 Ay', 'https://hukukcularevi.com/itirazin-kaldirilmasi-talebi-dilekcesi-ornegi-iik-68/'),
('İcra ve İflas Hukuku', 'Kefalet Nedeniyle Takibe Menfi Tespit Dava Dilekçesi Örneği (2026) — TBK m.583-5', 'https://hukukcularevi.com/kefalete-dayali-takibe-menfi-tespit-dava-dilekcesi-ornegi-tbk-583-584/'),
('İcra ve İflas Hukuku', 'İcranın Geri Bırakılması Talebi Dilekçesi Örneği (2026) — İİK m.33 ve 7 Gün', 'https://hukukcularevi.com/icranin-geri-birakilmasi-talebi-dilekcesi-ornegi-iik-33/'),
('Konkordato', 'Konkordato Alacak Kaydı Dilekçesi Örneği (İİK m.299) — 15 Günlük Süre ve Ekler', 'https://hukukcularevi.com/konkordato-alacak-kaydi-dilekcesi-ornegi/'),
('Konkordato', 'Konkordato Geçici Mühlete İtiraz Dilekçesi Örneği (İİK m.288) — 7 Günlük Kesin S', 'https://hukukcularevi.com/konkordato-gecici-muhlete-itiraz-dilekcesi-ornegi/'),
('Konkordato', 'Konkordatoda Rehinli Alacaklı: Kıymet Takdirine İtiraz ve Rehin Açığı Dilekçesi', 'https://hukukcularevi.com/konkordato-rehinli-alacakli-kiymet-takdirine-itiraz-dilekcesi/'),
('Konkordato', 'Konkordatoda Çekişmeli Alacak Davası Dilekçesi Örneği (İİK m.308/b) — 1 Aylık Sü', 'https://hukukcularevi.com/konkordato-cekismeli-alacak-davasi-dilekcesi-ornegi/'),
('Konkordato', 'Konkordatonun Feshi Talebi Dilekçesi Örneği (İİK m.308/e ve m.308/f)', 'https://hukukcularevi.com/konkordatonun-feshi-talebi-dilekcesi-ornegi/'),
('Konkordato', 'Konkordato Dilekçe Örnekleri (2026) — Alacaklı ve Borçlu İçin 9 Hazır Dilekçe', 'https://hukukcularevi.com/konkordato-dilekce-ornekleri/'),
('Konkordato', 'Konkordato Talebi Dilekçesi Örneği (İİK m.285-286) — Belgeler, Yetkili Mahkeme v', 'https://hukukcularevi.com/konkordato-talebi-dilekcesi-ornegi/'),
('Konkordato', 'Konkordato Mühlet Uzatma Talebi Dilekçesi (İİK m.287 ve m.289) — 3+2 ve 12+6 Ay', 'https://hukukcularevi.com/konkordato-muhlet-uzatma-talebi-dilekcesi-ornegi/'),
('Konkordato', 'Konkordato Mühletinde Mahkeme İzni Talebi Dilekçesi (İİK m.297) — İzne Tabi İşle', 'https://hukukcularevi.com/konkordato-muhlette-mahkeme-izni-talebi-dilekcesi/'),
('Konkordato', 'Konkordatoda Rehinli Alacaklılarla Müzakere Talebi Dilekçesi (İİK m.308/h) — Üçt', 'https://hukukcularevi.com/konkordato-rehinli-alacaklilarla-muzakere-talebi-dilekcesi/'),
('Ceza ve İnfaz Hukuku', 'Adli Sicil / Arşiv Kaydı Silme ve Memnu Hakların İadesi Dilekçesi (2026)', 'https://hukukcularevi.com/adli-sicil-arsiv-kaydi-silme-dilekcesi-ornegi/'),
('Ceza ve İnfaz Hukuku', 'Ceza ve İnfaz Hukuku Örnek Dilekçeler (2026)', 'https://hukukcularevi.com/ceza-infaz-hukuku-ornek-dilekceler/'),
('Ceza ve İnfaz Hukuku', 'Denetimli Serbestlik Talebi Dilekçesi Örneği (2026) — 5275 m.105/A', 'https://hukukcularevi.com/denetimli-serbestlik-talebi-dilekcesi-ornegi/'),
('Ceza ve İnfaz Hukuku', 'Dilekçe Hakkı: İdareye Şikâyet ve İstek Başvurusu Nasıl Yapılır? (3071 Sayılı Ka', 'https://hukukcularevi.com/dilekce-hakki-idareye-sikayet-ve-istek-basvurusu/'),
('Ceza ve İnfaz Hukuku', 'Fon Mağduru Savcılığa Şikâyet Dilekçesi Örneği (2026) — Fon Yöneticilerine Karşı', 'https://hukukcularevi.com/fon-magduru-savciliga-sikayet-dilekcesi-ornegi-fon-yoneticileri-tck-155-158-spkn-110-115-cmk-158/'),
('Ceza ve İnfaz Hukuku', 'HAGB Kararına Karşı Dilekçe Örneği (2026): İtiraz mı İstinaf mı? Karar Tarihine', 'https://hukukcularevi.com/hagb-itiraz-dilekcesi-ornegi/'),
('Ceza ve İnfaz Hukuku', 'Müddetnameye İtiraz Dilekçesi Örneği (2026) — İnfaz Hâkimliğine', 'https://hukukcularevi.com/muddetnameye-itiraz-dilekcesi-ornegi/'),
('Ceza ve İnfaz Hukuku', 'Sulh Ceza Hâkimliğine İtiraz Dilekçesi (Trafik Cezası) — Şablon ve Rehber', 'https://hukukcularevi.com/sulh-ceza-hakimligine-itiraz-dilekcesi/'),
('Ceza ve İnfaz Hukuku', 'TCK 158/4 Uyarlama Dilekçesi Örneği: Hangi Mahkemeye, Nasıl Yazılır?', 'https://hukukcularevi.com/tck-158-4-uyarlama-dilekcesi-ornegi/'),
('Ceza ve İnfaz Hukuku', 'Takipsizlik (KYOK) Kararına İtiraz Dilekçesi Örneği (2026) — 15 Gün', 'https://hukukcularevi.com/takipsizlik-kararina-itiraz-dilekcesi-ornegi/'),
('Ceza ve İnfaz Hukuku', 'Şikâyet Dilekçesi Örneği (2026) — Cumhuriyet Başsavcılığına', 'https://hukukcularevi.com/sikayet-dilekcesi-ornegi-savcilik/'),
('Ceza ve İnfaz Hukuku', 'Tutuklamaya İtiraz ve Tahliye Talebi Dilekçesi Örneği (2026) — CMK m.100, 104, 2', 'https://hukukcularevi.com/tutuklamaya-itiraz-ve-tahliye-talebi-dilekcesi-ornegi/'),
('Ceza ve İnfaz Hukuku', 'Uzlaştırma Talebi ve Beyan Dilekçesi Örneği (2026) — CMK m.253 ve 7 Gün', 'https://hukukcularevi.com/uzlastirma-talebi-dilekcesi-ornegi-cmk-253/'),
('Ceza ve İnfaz Hukuku', 'HAGB Talebi Dilekçesi Örneği (2026) — 7589 Sonrası Yeni Rejim', 'https://hukukcularevi.com/hagb-talebi-dilekcesi-ornegi-cmk-231/'),
('Ceza ve İnfaz Hukuku', 'İnfazın Ertelenmesi Talebi Dilekçesi Örneği (2026) — 5275 m.16-17 ve 10 Gün', 'https://hukukcularevi.com/infazin-ertelenmesi-talebi-dilekcesi-ornegi-5275/'),
('Ceza ve İnfaz Hukuku', 'Adli Kontrolün Kaldırılması Talebi Dilekçesi Örneği (2026) — CMK m.111 ve 5 Gün', 'https://hukukcularevi.com/adli-kontrolun-kaldirilmasi-talebi-dilekcesi-ornegi-cmk-111/'),
('Ceza ve İnfaz Hukuku', 'Elkonulan Eşyanın İadesi Talebi Dilekçesi Örneği (2026) — CMK m.131', 'https://hukukcularevi.com/elkonulan-esyanin-iadesi-talebi-dilekcesi-ornegi-cmk-131/'),
('Ceza ve İnfaz Hukuku', 'Hakaret Şikâyet Dilekçesi Örneği (2026) — TCK m.125 ve İhtilat Şartı', 'https://hukukcularevi.com/hakaret-sikayet-dilekcesi-ornegi-tck-125/'),
('Ceza ve İnfaz Hukuku', 'Dolandırıcılık Şikâyet Dilekçesi Örneği (2026) — TCK m.157-158', 'https://hukukcularevi.com/dolandiricilik-sikayet-dilekcesi-ornegi-tck-157-158/'),
('Ceza ve İnfaz Hukuku', 'Tehdit Şikâyet Dilekçesi Örneği (2026) — TCK m.106', 'https://hukukcularevi.com/tehdit-sikayet-dilekcesi-ornegi-tck-106/'),
('Ceza ve İnfaz Hukuku', 'İmar Kirliliğine Neden Olma Savunma Dilekçesi Örneği (2026) — TCK m.184 ve Etkin', 'https://hukukcularevi.com/imar-kirliligine-neden-olma-savunma-dilekcesi-ornegi-tck-184/'),
('Gayrimenkul ve Kira Hukuku', 'Depozito İadesi İhtarnamesi ve Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/depozito-iadesi-ihtarname-dilekcesi-ornegi/'),
('Gayrimenkul ve Kira Hukuku', 'Kira Hukuku Rehberi: Tahliye, Kira Artışı, Depozito ve Dilekçeler', 'https://hukukcularevi.com/kira-hukuku-rehberi/'),
('Gayrimenkul ve Kira Hukuku', 'Kira Hukuku Örnek Dilekçeler (2026) — Kiracı ve Ev Sahibi İçin', 'https://hukukcularevi.com/kira-hukuku-ornek-dilekceler/'),
('Gayrimenkul ve Kira Hukuku', 'Kira Tespit Davası Dilekçesi Örneği (2026) — TBK 344', 'https://hukukcularevi.com/kira-tespit-dava-dilekcesi-ornegi/'),
('Gayrimenkul ve Kira Hukuku', 'Tahliye Davasına Cevap Dilekçesi Örneği (2026) — Kiracı Savunması', 'https://hukukcularevi.com/tahliye-davasina-cevap-dilekcesi-ornegi/'),
('Gayrimenkul ve Kira Hukuku', 'Tahliye Taahhüdüne Dayalı Tahliye Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/tahliye-taahhudune-dayali-tahliye-dilekcesi-ornegi/'),
('Gayrimenkul ve Kira Hukuku', 'İhtiyaç Nedeniyle Tahliye Dava Dilekçesi Örneği (2026) — TBK 350', 'https://hukukcularevi.com/ihtiyac-nedeniyle-tahliye-dava-dilekcesi-ornegi/'),
('Gayrimenkul ve Kira Hukuku', 'İki Haklı İhtar Nedeniyle Tahliye Dava Dilekçesi Örneği (2026) — TBK m.352/2', 'https://hukukcularevi.com/iki-hakli-ihtar-nedeniyle-tahliye-dava-dilekcesi-ornegi/'),
('Gayrimenkul ve Kira Hukuku', 'Kat Malikleri Kurulu Kararının İptali Dava Dilekçesi Örneği (2026) — KMK m.33', 'https://hukukcularevi.com/kat-malikleri-kurulu-karari-iptali-dava-dilekcesi-ornegi/'),
('Gayrimenkul ve Kira Hukuku', 'Aidat (Ortak Gider) Alacağının Tahsili Dava Dilekçesi Örneği (2026) — KMK m.20', 'https://hukukcularevi.com/aidat-ortak-gider-alacagi-dava-dilekcesi-ornegi/'),
('Gayrimenkul ve Kira Hukuku', 'Önalım (Şufa) Dava Dilekçesi Örneği (2026) — 7571 Sonrası Rayiç Bedel ve 1 Yıl', 'https://hukukcularevi.com/onalim-sufa-dava-dilekcesi-ornegi/'),
('Gayrimenkul ve Kira Hukuku', 'Kat Karşılığı İnşaat Sözleşmesi Fesih Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/kat-karsiligi-insaat-sozlesmesi-fesih-dava-dilekcesi-ornegi/'),
('Gayrimenkul ve Kira Hukuku', 'Ortak Alana El Atmanın Önlenmesi ve Eski Hâle Getirme Dilekçesi Örneği (2026) —', 'https://hukukcularevi.com/ortak-alana-el-atmanin-onlenmesi-eski-hale-getirme-dilekcesi-ornegi/'),
('Gayrimenkul ve Kira Hukuku', 'Ecrimisil (Haksız İşgal Tazminatı) Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/ecrimisil-haksiz-isgal-tazminati-dava-dilekcesi-ornegi/'),
('Gayrimenkul ve Kira Hukuku', 'Komşu Gürültüsü ve Müdahalenin Önlenmesi Dava Dilekçesi Örneği (2026) — TMK m.73', 'https://hukukcularevi.com/komsu-gurultusu-mudahalenin-onlenmesi-dava-dilekcesi-ornegi-tmk-737-kmk-33/'),
('Gayrimenkul ve Kira Hukuku', 'Arsa Payının Düzeltilmesi Dava Dilekçesi Örneği (2026) — KMK m.3', 'https://hukukcularevi.com/arsa-payinin-duzeltilmesi-dava-dilekcesi-ornegi-kmk-3/'),
('Gayrimenkul ve Kira Hukuku', 'Muhdesatın Aidiyetinin Tespiti Dava Dilekçesi Örneği (2026) — HMK m.106', 'https://hukukcularevi.com/muhdesatin-aidiyetinin-tespiti-dava-dilekcesi-ornegi-hmk-106/'),
('Gayrimenkul ve Kira Hukuku', 'Elbirliği Mülkiyetinin Paylı Mülkiyete Dönüştürülmesi Dava Dilekçesi Örneği (202', 'https://hukukcularevi.com/elbirligi-mulkiyetinin-payli-mulkiyete-donusturulmesi-dilekcesi-tmk-644/'),
('Gayrimenkul ve Kira Hukuku', 'Taşkın Yapı ve Temliken Tescil Dava Dilekçesi Örneği (2026) — TMK m.725 ve On Be', 'https://hukukcularevi.com/taskin-yapi-temliken-tescil-dava-dilekcesi-ornegi-tmk-725/'),
('Gayrimenkul ve Kira Hukuku', 'Kat Mülkiyetinin Devri Dava Dilekçesi Örneği (2026) — KMK m.25 ve Çekilmezlik', 'https://hukukcularevi.com/kat-mulkiyetinin-devri-dava-dilekcesi-ornegi-kmk-25/'),
('Gayrimenkul ve Kira Hukuku', 'Olağanüstü Zamanaşımı ile Tescil Dava Dilekçesi Örneği (2026) — TMK m.713 ve Yir', 'https://hukukcularevi.com/olaganustu-zamanasimi-tescil-dava-dilekcesi-ornegi-tmk-713/'),
('Gayrimenkul ve Kira Hukuku', 'Tapu İptali ve Tescil Dava Dilekçesi Örneği (2026) — Yolsuz Tescil ve TMK m.1025', 'https://hukukcularevi.com/tapu-iptali-ve-tescil-dava-dilekcesi-ornegi-tmk-1025/'),
('Gayrimenkul ve Kira Hukuku', 'Zorunlu Geçit Hakkı Dava Dilekçesi Örneği (2026) — TMK m.747 ve Tam Bedel', 'https://hukukcularevi.com/zorunlu-gecit-hakki-dava-dilekcesi-ornegi-tmk-747/'),
('Gayrimenkul ve Kira Hukuku', 'Kira Ödenmemesi İhtarnamesi Örneği (2026) — 30 Günlük Süre', 'https://hukukcularevi.com/kira-odenmemesi-ihtarname-ornegi/'),
('Gayrimenkul ve Kira Hukuku', 'Temerrüt Nedeniyle Tahliye Dava Dilekçesi Örneği (2026) — TBK m.315 ve Otuz Gün', 'https://hukukcularevi.com/temerrut-nedeniyle-tahliye-dava-dilekcesi-ornegi-tbk-315/'),
('Gayrimenkul ve Kira Hukuku', 'Yeni Malikin Gereksinimi Nedeniyle Tahliye Dava Dilekçesi Örneği (2026) — TBK m.', 'https://hukukcularevi.com/yeni-malikin-gereksinimi-tahliye-dava-dilekcesi-ornegi-tbk-351/'),
('Gayrimenkul ve Kira Hukuku', 'Yeniden İnşa ve Esaslı Onarım Nedeniyle Tahliye Dava Dilekçesi Örneği (2026) — T', 'https://hukukcularevi.com/yeniden-insa-esasli-onarim-tahliye-dava-dilekcesi-ornegi-tbk-350/'),
('Gayrimenkul ve Kira Hukuku', 'Depozito (Güvence Bedeli) İadesi Dava Dilekçesi Örneği (2026) — TBK m.342', 'https://hukukcularevi.com/depozito-guvence-bedeli-iadesi-dava-dilekcesi-ornegi-tbk-342/'),
('Gayrimenkul ve Kira Hukuku', 'Erken Tahliyede Kira Alacağına Cevap Dilekçesi Örneği (2026) — TBK m.325 ve Maku', 'https://hukukcularevi.com/erken-tahliye-kira-alacagi-cevap-dilekcesi-ornegi-tbk-325/'),
('Gayrimenkul ve Kira Hukuku', 'Tapu Tahsis Belgesine Dayalı Tapu İptali ve Tescil Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/tapu-tahsis-belgesi-tapu-iptali-tescil-dava-dilekcesi-ornegi-2981/'),
('Gayrimenkul ve Kira Hukuku', 'Meskenin İşyerine Çevrilmesi Dava Dilekçesi Örneği (2026) — KMK m.24', 'https://hukukcularevi.com/mesken-isyerine-cevirme-mudahalenin-onlenmesi-dava-dilekcesi-ornegi-kmk-24/'),
('Gayrimenkul ve Kira Hukuku', 'Yapı Hasarı Tazminat Dava Dilekçesi Örneği (2026) — 4708 Yapı Denetimi m.3', 'https://hukukcularevi.com/yapi-hasari-tazminat-dava-dilekcesi-ornegi-4708-yapi-denetim/'),
('Gayrimenkul ve Kira Hukuku', 'Komşu Kazı ve İnşaat Nedeniyle Bina Hasarı Tazminat Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/komsu-kazi-insaat-nedeniyle-bina-hasari-tazminat-dava-dilekcesi-ornegi/'),
('Gayrimenkul ve Kira Hukuku', 'Kat Malikleri Kurulu Kararının İptali Dava Dilekçesi Örneği (2026) — KMK m.33', 'https://hukukcularevi.com/kat-malikleri-kurulu-karari-iptal-dava-dilekcesi-ornegi-kmk-33/'),
('Gayrimenkul ve Kira Hukuku', 'Tapu Kaydında Düzeltim Dava Dilekçesi Örneği (2026) — TMK m.1027', 'https://hukukcularevi.com/tapu-kaydinda-duzeltim-dava-dilekcesi-ornegi-tmk-1027/'),
('Gayrimenkul ve Kira Hukuku', 'Ayıplı ve Eksik Konut Dava Dilekçesi Örneği (2026) — TKHK m.11, TBK m.478', 'https://hukukcularevi.com/ayipli-ve-eksik-konut-dava-dilekcesi-ornegi-tkhk-11-tbk-478/'),
('Gayrimenkul ve Kira Hukuku', 'Satış Vaadine Dayalı Tapu İptali ve Tescil Dava Dilekçesi Örneği (2026) — TBK m.', 'https://hukukcularevi.com/satis-vaadine-dayali-tapu-iptali-tescil-dava-dilekcesi-ornegi-tbk-237/'),
('Gayrimenkul ve Kira Hukuku', 'Ön Ödemeli Konut Satışında Dönme ve Bedel İadesi Dava Dilekçesi Örneği (2026) —', 'https://hukukcularevi.com/on-odemeli-konut-satisindan-donme-bedel-iadesi-dava-dilekcesi-ornegi-6502-45/'),
('Gayrimenkul ve Kira Hukuku', 'Devre Tatil ve Devre Mülk Sözleşmesinin İptali Dava Dilekçesi Örneği (2026) — 65', 'https://hukukcularevi.com/devre-tatil-devre-mulk-sozlesmesi-iptal-dava-dilekcesi-ornegi-6502-50/'),
('Gayrimenkul ve Kira Hukuku', 'İpoteğin Fekki (Terkini) Dava Dilekçesi Örneği (2026) — TMK m.883', 'https://hukukcularevi.com/ipotegin-fekki-terkini-dava-dilekcesi-ornegi-tmk-883/'),
('Gayrimenkul ve Kira Hukuku', 'Emlakçı Komisyonuna İtiraz ve Menfi Tespit Dava Dilekçesi Örneği (2026) — TBK m.', 'https://hukukcularevi.com/emlakci-komisyonu-itiraz-menfi-tespit-dava-dilekcesi-ornegi-tbk-520/'),
('Gayrimenkul ve Kira Hukuku', 'Kira Bedelinin Tespiti Dava Dilekçesi Örneği (2026) — TBK m.344, 345', 'https://hukukcularevi.com/kira-bedelinin-tespiti-dava-dilekcesi-ornegi-tbk-344-345/'),
('Gayrimenkul ve Kira Hukuku', 'Kira Uyarlama Dava Dilekçesi Örneği (2026) — TBK m.138 Aşırı İfa Güçlüğü', 'https://hukukcularevi.com/kira-uyarlama-dava-dilekcesi-ornegi-tbk-138/'),
('Gayrimenkul ve Kira Hukuku', 'Sitede (Toplu Yapıda) Ortak Gidere ve Kurul Kararına İtiraz Dilekçesi Örneği (20', 'https://hukukcularevi.com/site-toplu-yapi-ortak-gider-itiraz-dava-dilekcesi-ornegi-kmk-69-73/'),
('Gayrimenkul ve Kira Hukuku', 'Yapı Malikinin Sorumluluğu Tazminat Dava Dilekçesi Örneği (2026) — TBK m.69, 70', 'https://hukukcularevi.com/yapi-malikinin-sorumlulugu-tazminat-dava-dilekcesi-ornegi-tbk-69/'),
('Gayrimenkul ve Kira Hukuku', 'Engellinin Erişimi İçin Proje Tadili Başvuru ve Dava Dilekçesi Örneği (2026) — K', 'https://hukukcularevi.com/engelli-erisimi-proje-tadili-basvuru-dava-dilekcesi-ornegi-kmk-42/'),
('Gayrimenkul ve Kira Hukuku', 'Kat İrtifakından Kat Mülkiyetine Geçiş Başvuru ve Dava Dilekçesi Örneği (2026) —', 'https://hukukcularevi.com/kat-irtifakindan-kat-mulkiyetine-gecis-basvuru-dava-dilekcesi-ornegi-kmk-14/'),
('Gayrimenkul ve Kira Hukuku', 'Geç Teslimde Gecikme Tazminatı ve Kira Kaybı Dava Dilekçesi Örneği (2026) — TBK', 'https://hukukcularevi.com/muteahhit-gecikme-tazminati-kira-kaybi-dava-dilekcesi-ornegi-tbk-118-125/'),
('Gayrimenkul ve Kira Hukuku', 'El Atmanın Önlenmesi (Müdahalenin Meni) Dava Dilekçesi Örneği (2026) — TMK m.683', 'https://hukukcularevi.com/el-atmanin-onlenmesi-mudahalenin-meni-dava-dilekcesi-ornegi-tmk-683/'),
('Gayrimenkul ve Kira Hukuku', 'Kat ve Bağımsız Bölüm İlavesinde Eski Hâle Getirme Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/bagimsiz-bolum-kat-ilavesi-eski-hale-getirme-dava-dilekcesi-ornegi-kmk-44/'),
('Gayrimenkul ve Kira Hukuku', 'Vekâletin Kötüye Kullanılması ile Tapu İptali ve Tescil Dava Dilekçesi Örneği (2', 'https://hukukcularevi.com/vekaletin-kotuye-kullanilmasi-tapu-iptali-tescil-dava-dilekcesi-ornegi-tbk-504/'),
('Gayrimenkul ve Kira Hukuku', 'Yükleniciden Daire Alan Üçüncü Kişinin Tapu İptali ve Tescil Dava Dilekçesi Örne', 'https://hukukcularevi.com/yukleniciden-daire-alan-ucuncu-kisi-tapu-iptali-tescil-dava-dilekcesi-ornegi/'),
('Gayrimenkul ve Kira Hukuku', 'Ehliyetsizlik Nedeniyle Tapu İptali ve Tescil Dava Dilekçesi Örneği (2026) — TMK', 'https://hukukcularevi.com/ehliyetsizlik-nedeniyle-tapu-iptali-tescil-dava-dilekcesi-ornegi-tmk-15/'),
('Gayrimenkul ve Kira Hukuku', 'Kapora (Pey Akçesi) İadesi Dava Dilekçesi Örneği (2026) — TBK m.177, 178', 'https://hukukcularevi.com/kapora-pey-akcesi-iadesi-dava-dilekcesi-ornegi-tbk-177-178/'),
('Gayrimenkul ve Kira Hukuku', 'Yöneticiden Hesap Sorma, Azil ve Yönetici Atanması Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/yonetici-hesap-verme-azil-yonetici-atanmasi-dava-dilekcesi-ornegi-kmk-34-39/'),
('Gayrimenkul ve Kira Hukuku', 'İkinci El Konutta Gizli Ayıp ve Bedel İndirimi Dava Dilekçesi Örneği (2026) — TB', 'https://hukukcularevi.com/ikinci-el-konutta-gizli-ayip-bedel-indirimi-dava-dilekcesi-ornegi-tbk-219/'),
('Gayrimenkul ve Kira Hukuku', 'Kira Sözleşmesinde Kefaletin Geçersizliği ve Menfi Tespit Dava Dilekçesi Örneği', 'https://hukukcularevi.com/kira-sozlesmesinde-kefaletin-gecersizligi-menfi-tespit-dava-dilekcesi-ornegi-tbk-583/'),
('Gayrimenkul ve Kira Hukuku', 'Kiralananın Ayıbı, Kira İndirimi ve Giderim Dava Dilekçesi Örneği (2026) — TBK m', 'https://hukukcularevi.com/kiralananin-ayibi-kira-indirimi-dava-dilekcesi-ornegi-tbk-305-307/'),
('Gayrimenkul ve Kira Hukuku', 'İşyeri Kirasının Devri ve Rıza Yerine Geçen Karar Dava Dilekçesi Örneği (2026) —', 'https://hukukcularevi.com/isyeri-kirasinin-devri-riza-yerine-gecen-karar-dava-dilekcesi-ornegi-tbk-323/'),
('Gayrimenkul ve Kira Hukuku', 'İki Haklı İhtar Nedeniyle Tahliye Dava Dilekçesi Örneği (2026) — TBK m.352/2', 'https://hukukcularevi.com/iki-hakli-ihtar-nedeniyle-tahliye-dava-dilekcesi-ornegi-tbk-352/'),
('Gayrimenkul ve Kira Hukuku', 'Kiracının Ölümünde Kira Sözleşmesinin Sürdürülmesi Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/kiracinin-olumunde-kira-sozlesmesinin-surdurulmesi-dava-dilekcesi-ornegi-tbk-356/'),
('Kamulaştırma', 'Kamulaştırmasız El Atma Dava Dilekçesi Örneği (2026) — Fiilî ve Hukuki El Atma', 'https://hukukcularevi.com/kamulastirmasiz-el-atma-dava-dilekcesi-ornegi/'),
('Kamulaştırma', 'Kamulaştırmada Uzlaşma Başvuru Dilekçesi Örneği (2026) — 2942 s.K. m.8', 'https://hukukcularevi.com/kamulastirmada-uzlasma-basvuru-dilekcesi-ornegi-2942-8/'),
('Kamulaştırma', 'Tapusuz Taşınmazın Kamulaştırılması ve Zilyedin Hakları Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/tapusuz-tasinmazin-kamulastirilmasi-zilyet-beyan-dilekcesi-ornegi-2942-19/'),
('Kamulaştırma', 'Kamulaştırılan Taşınmazda Kiracının Hakları Dava Dilekçesi Örneği (2026) — 2942', 'https://hukukcularevi.com/kamulastirilan-tasinmazda-kiracinin-haklari-dava-dilekcesi-ornegi-2942-20/'),
('Kamulaştırma', 'İrtifak Kamulaştırmasında Değer Düşüklüğü ve Bilirkişi Raporuna İtiraz Dilekçesi', 'https://hukukcularevi.com/irtifak-kamulastirmasi-deger-dusuklugu-rapora-itiraz-dilekcesi-ornegi/'),
('Kamulaştırma', 'Kamulaştırma Bedel Tespiti ve Tescil Davasında Cevap Dilekçesi Örneği (2026) — 2', 'https://hukukcularevi.com/kamulastirma-bedel-tespiti-tescil-davasi-cevap-dilekcesi-ornegi/'),
('Kamulaştırma', 'Acele Kamulaştırma Kararının İptali Dava Dilekçesi Örneği (2026) — 2942 m.27 ve', 'https://hukukcularevi.com/acele-kamulastirma-iptal-dava-dilekcesi-ornegi-2942-27/'),
('Kamulaştırma', 'Kamulaştırma Uzlaşma Davetine Cevap Dilekçesi Örneği (2026) — 2942 m.8 ve On Beş', 'https://hukukcularevi.com/kamulastirma-uzlasma-davetine-cevap-dilekcesi-ornegi-2942-8/'),
('Kamulaştırma', 'Kamulaştırmasız El Atmada Uzlaşma Başvurusu Dilekçesi Örneği (2026) — Geçici m.6', 'https://hukukcularevi.com/kamulastirmasiz-el-atma-uzlasma-basvurusu-dilekcesi-ornegi-gecici-6/'),
('Kamulaştırma', 'Kamulaştırmada Maddi Hataya Karşı Düzeltim Davası Dilekçesi Örneği (2026) — 2942', 'https://hukukcularevi.com/kamulastirmada-maddi-hata-duzeltim-davasi-dilekcesi-ornegi-2942-14/'),
('Kamulaştırma', 'Kamulaştırmadan Vazgeçme ve Taşınmazın İadesi Dilekçesi Örneği (2026) — 2942 m.2', 'https://hukukcularevi.com/kamulastirmadan-vazgecme-tasinmazin-iadesi-dilekcesi-ornegi-2942-22/'),
('Kamulaştırma', 'Kamulaştırma Bedeline İstihkak Davası Dilekçesi Örneği (2026) — 2942 m.18 ve Blo', 'https://hukukcularevi.com/kamulastirma-bedeline-istihkak-davasi-dilekcesi-ornegi-2942-18/'),
('Kamulaştırma', 'Kamulaştırmada AİHM Başvurusu Dilekçesi Örneği (2026) — Dört Ay ve Mülkiyet Hakk', 'https://hukukcularevi.com/kamulastirmada-aihm-basvurusu-dilekcesi-ornegi-dort-ay/'),
('Kamulaştırma', 'Kamulaştırılan Taşınmazın Boşaltılması ve Ekili Arazi Dilekçesi Örneği (2026) —', 'https://hukukcularevi.com/kamulastirilan-tasinmazin-bosaltilmasi-ekili-arazi-dilekcesi-ornegi-2942-20/'),
('Kamulaştırma', 'Kamulaştırmada Anayasa Mahkemesine Bireysel Başvuru Dilekçesi Örneği (2026) — Ot', 'https://hukukcularevi.com/kamulastirmada-anayasa-mahkemesi-bireysel-basvuru-dilekcesi-ornegi/'),
('Kamulaştırma', 'Kamulaştırma Bedelini Ödemeyen İdareye Karşı İcra ve Haciz Dilekçesi Örneği (202', 'https://hukukcularevi.com/kamulastirma-bedelini-odemeyen-idareye-karsi-icra-haciz-dilekcesi-ornegi/'),
('Kamulaştırma', 'Hisseli Taşınmazın Kamulaştırılmasında Paydaşın Beyan Dilekçesi Örneği (2026) —', 'https://hukukcularevi.com/hisseli-tasinmaz-kamulastirma-paydas-beyan-dilekcesi-ornegi-2942-12/'),
('Kamulaştırma', 'Kamulaştırma Bedeline İtiraz Dilekçesi Örneği (2026) — Bilirkişi Raporuna Karşı', 'https://hukukcularevi.com/kamulastirma-bedeline-itiraz-dilekcesi-ornegi/'),
('Kamulaştırma', 'Kamulaştırma İşleminin İptali Dava Dilekçesi Örneği (2026) — 30 Gün ve İdari Yar', 'https://hukukcularevi.com/kamulastirma-isleminin-iptali-dava-dilekcesi-ornegi/'),
('Kamulaştırma', 'Kamulaştırılan Taşınmazın Geri Alınması Dava Dilekçesi Örneği (2026) — 2942 s.K.', 'https://hukukcularevi.com/kamulastirilan-tasinmazin-geri-alinmasi-dava-dilekcesi-ornegi/'),
('Kamulaştırma', 'Artan Kısım ve Baraj Mücavir Alan Kamulaştırma Talebi Dilekçe Örnekleri (2026) —', 'https://hukukcularevi.com/artan-kismin-kamulastirilmasi-talebi-dilekce-ornegi/'),
('Kamulaştırma', 'Kamulaştırma Şerhinin Terkini Talebi Dilekçesi Örneği (2026) — 2942 s.K. m.7 ve', 'https://hukukcularevi.com/kamulastirma-serhinin-terkini-talebi-dilekce-ornegi/'),
('Kamulaştırma', 'Kamulaştırma Dilekçe Örnekleri (2026) — 6 Hazır Dilekçe ve Süre Haritası', 'https://hukukcularevi.com/kamulastirma-dilekce-ornekleri/'),
('Kamulaştırma', 'Tapusuz Taşınmazın Kamulaştırılmasında Zilyedin Beyan Dilekçesi Örneği (2026) —', 'https://hukukcularevi.com/tapusuz-tasinmaz-kamulastirma-zilyet-beyan-dilekcesi-ornegi-2942-19/'),
('Kamulaştırma', 'Kamulaştırma Bedel Tespiti Kararına Karşı İstinaf Dilekçesi Örneği (2026) — 2942', 'https://hukukcularevi.com/kamulastirma-bedel-tespiti-istinaf-dilekcesi-ornegi-2942-10/'),
('Kamulaştırma', 'Kamulaştırma Bedelinin Ödenmesi ve Tahsili Dilekçesi Örneği (2026) — 2942 m.10', 'https://hukukcularevi.com/kamulastirma-bedelinin-odenmesi-tahsili-dilekce-ornegi-2942-10/'),
('Kamulaştırma', 'Turizm Bölgesinde Acele Kamulaştırma ve Tahsis Dava Dilekçesi Örneği (2026) — 26', 'https://hukukcularevi.com/turizm-bolgesinde-acele-kamulastirma-tahsis-dava-dilekcesi-ornegi-2634/'),
('İmar ve Yapı', 'Yapı Kayıt Belgesinin İptaline Karşı Dava Dilekçesi Örneği (2026) — 3194 Geçici', 'https://hukukcularevi.com/yapi-kayit-belgesi-iptali-dava-dilekcesi-ornegi-3194-gecici-16/'),
('İmar ve Yapı', 'Yapı Ruhsatı Başvurusunun Reddine Karşı Dava Dilekçesi Örneği (2026) — İmar m.22', 'https://hukukcularevi.com/yapi-ruhsati-basvurusunun-reddi-dava-dilekcesi-ornegi/'),
('İmar ve Yapı', 'İskân (Yapı Kullanma İzni) Reddine Karşı Dava Dilekçesi Örneği (2026) — İmar m.3', 'https://hukukcularevi.com/iskan-yapi-kullanma-izni-reddi-dava-dilekcesi-ornegi/'),
('İmar ve Yapı', 'Yapı Ruhsatının İptali Dava Dilekçesi Örneği (2026) — Komşu Parsel Maliki ve Öğr', 'https://hukukcularevi.com/yapi-ruhsatinin-iptali-dava-dilekcesi-ornegi/'),
('İmar ve Yapı', 'İmar Planının İptali Dava Dilekçesi Örneği (2026) — İmar m.8 ve Beş Yıllık Sınır', 'https://hukukcularevi.com/imar-plani-iptal-dava-dilekcesi-ornegi-3194-8/'),
('İmar ve Yapı', 'Parselasyon (İmar m.18) İşleminin İptali Dava Dilekçesi Örneği (2026) — DOP ve T', 'https://hukukcularevi.com/parselasyon-iptali-dava-dilekcesi-ornegi-imar-18/'),
('İmar ve Yapı', 'İmar Planına Askı Süresinde İtiraz Dilekçesi Örneği (2026) — İmar m.8/b ve Bir A', 'https://hukukcularevi.com/imar-planina-aski-suresinde-itiraz-dilekcesi-ornegi/'),
('İmar ve Yapı', 'Metruk ve Tehlikeli Yapı Yıkım İşleminin İptali Dava Dilekçesi Örneği (2026) — İ', 'https://hukukcularevi.com/metruk-tehlikeli-yapi-yikim-itiraz-dilekcesi-ornegi/'),
('İmar ve Yapı', 'Yıkım Kararının İptali Dava Dilekçesi Örneği (2026) — İmar m.32 ve Bir Aylık Sür', 'https://hukukcularevi.com/yikim-karari-iptal-dava-dilekcesi-ornegi-imar-32/'),
('İmar ve Yapı', 'İmar Para Cezasının İptali Dava Dilekçesi Örneği (2026) — İmar m.42 ve 60 Gün', 'https://hukukcularevi.com/imar-para-cezasi-iptal-dava-dilekcesi-ornegi/'),
('İmar ve Yapı', 'İskânsız Yapıya Geçici Elektrik ve Su Aboneliği Başvuru ve Dava Dilekçesi Örneği', 'https://hukukcularevi.com/iskansiz-ruhsatsiz-yapiya-gecici-abonelik-basvuru-dava-dilekcesi-ornegi/'),
('İmar ve Yapı', 'Köy Yerleşik Alanında Yapı ve Yıkım Kararının İptali Dava Dilekçesi Örneği (2026', 'https://hukukcularevi.com/koy-yerlesik-alaninda-yapi-yikim-karari-iptal-dava-dilekcesi-ornegi-imar-27/'),
('İmar ve Yapı', 'İfraz ve Tevhit Talebinin Reddi Dava Dilekçesi Örneği (2026) — İmar m.15-16', 'https://hukukcularevi.com/ifraz-tevhit-talebinin-reddi-dava-dilekcesi-ornegi-imar-15-16/'),
('İmar ve Yapı', 'Muvakkat Yapı (Geçici İnşaat Ruhsatı) Başvuru ve Dava Dilekçesi Örneği (2026) —', 'https://hukukcularevi.com/muvakkat-yapi-gecici-insaat-ruhsati-basvuru-dava-dilekcesi-ornegi-imar-33/'),
('İmar ve Yapı', 'Sit Alanında Yapılaşma İzni, Trampa ve Kurul Kararına Dava Dilekçesi Örneği (202', 'https://hukukcularevi.com/sit-alaninda-yapilasma-izni-trampa-dava-dilekcesi-ornegi-2863/'),
('Kentsel Dönüşüm ve Afet', 'Riskli Yapı Tespitine İtiraz Dilekçesi Örneği (2026) — 6306 ve 15 Gün', 'https://hukukcularevi.com/riskli-yapi-tespitine-itiraz-dilekcesi-ornegi/'),
('Kentsel Dönüşüm ve Afet', 'Riskli Alan Kararının İptali Dava Dilekçesi Örneği (2026) — 6306 ve Danıştay', 'https://hukukcularevi.com/riskli-alan-karari-iptal-dava-dilekcesi-ornegi-6306/'),
('Kentsel Dönüşüm ve Afet', 'Riskli Yapıda Tahliye ve Yıkım İşleminin İptali Dava Dilekçesi Örneği (2026) — 6', 'https://hukukcularevi.com/riskli-yapi-tahliye-yikim-iptal-dava-dilekcesi-ornegi-6306-5/'),
('Kentsel Dönüşüm ve Afet', 'Kentsel Dönüşümde Arsa Payı Satışının İptali Dava Dilekçesi Örneği (2026) — 6306', 'https://hukukcularevi.com/kentsel-donusum-arsa-payi-satisi-iptal-dava-dilekcesi-ornegi/'),
('Kentsel Dönüşüm ve Afet', 'Afette Hasar Tespitine İtiraz ve Hak Sahipliği Dilekçesi Örneği (2026) — 7269 m.', 'https://hukukcularevi.com/afet-hasar-tespitine-itiraz-hak-sahipligi-dava-dilekcesi-ornegi-7269/'),
('Kentsel Dönüşüm ve Afet', 'Kentsel Dönüşüm ve Gelişim Alanı İlanının İptali Dava Dilekçesi Örneği (2026) —', 'https://hukukcularevi.com/kentsel-donusum-gelisim-alani-ilani-iptal-dava-dilekcesi-ornegi-belediye-73/'),
('Kentsel Dönüşüm ve Afet', 'Kentsel Dönüşümde Kira Yardımı Başvuru ve Dava Dilekçesi Örneği (2026) — 6306 m.', 'https://hukukcularevi.com/kentsel-donusum-kira-yardimi-basvuru-dava-dilekcesi-ornegi-6306-5/'),
('Kentsel Dönüşüm ve Afet', 'Rezerv Yapı Alanı Belirlenmesinin İptali Dava Dilekçesi Örneği (2026) — 6306 m.2', 'https://hukukcularevi.com/rezerv-yapi-alani-belirlenmesi-iptal-dava-dilekcesi-ornegi-6306-2/'),
('Arazi, Orman ve Hazine Taşınmazları', 'Kadastro Tespitine İtiraz Dava Dilekçesi Örneği (2026) — 3402 s.K. m.12', 'https://hukukcularevi.com/kadastro-tespitine-itiraz-dava-dilekcesi-ornegi-3402-12/'),
('Arazi, Orman ve Hazine Taşınmazları', 'Tarım Arazisinde Tarım Dışı Kullanım İzni Başvuru ve Dava Dilekçesi Örneği (2026', 'https://hukukcularevi.com/tarim-arazisi-tarim-disi-kullanim-izni-basvuru-dava-dilekcesi-ornegi-5403/'),
('Arazi, Orman ve Hazine Taşınmazları', 'Orman Kadastrosuna İtiraz Dava Dilekçesi Örneği (2026) — 6831 m.11', 'https://hukukcularevi.com/orman-kadastrosuna-itiraz-dava-dilekcesi-ornegi-6831-11/'),
('Arazi, Orman ve Hazine Taşınmazları', 'Mera Tespit ve Tahdidine İtiraz Dava Dilekçesi Örneği (2026) — 4342 Mera Kanunu', 'https://hukukcularevi.com/mera-tespit-tahdide-itiraz-dava-dilekcesi-ornegi-4342/'),
('Arazi, Orman ve Hazine Taşınmazları', 'Hazine Taşınmazında Ecrimisil İhbarnamesine İtiraz Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/hazine-tasinmazi-ecrimisil-ihbarnamesine-itiraz-dava-dilekcesi-ornegi-2886-75/'),
('Arazi, Orman ve Hazine Taşınmazları', 'Yabancının Taşınmaz Ediniminde Red ve Tasfiyeye İtiraz Dava Dilekçesi Örneği (20', 'https://hukukcularevi.com/yabancinin-tasinmaz-edinimi-red-tasfiye-dava-dilekcesi-ornegi-tapu-kanunu-35/'),
('Arazi, Orman ve Hazine Taşınmazları', 'Kamu Konutu (Lojman) Tahliye İşlemine İtiraz Dava Dilekçesi Örneği (2026) — 2946', 'https://hukukcularevi.com/kamu-konutu-lojman-tahliye-islemine-itiraz-dava-dilekcesi-ornegi-2946/'),
('Arazi, Orman ve Hazine Taşınmazları', 'Hazine Taşınmazının Doğrudan Satışı ve Kiralanması Başvuru Dilekçesi Örneği (202', 'https://hukukcularevi.com/hazine-tasinmazi-dogrudan-satis-kiralama-basvuru-dava-dilekcesi-ornegi-4706/'),
('Arazi, Orman ve Hazine Taşınmazları', 'Kooperatif Ortaklıktan Çıkarma Kararına İtiraz Dava Dilekçesi Örneği (2026) — 11', 'https://hukukcularevi.com/kooperatif-ortakliktan-cikarma-itiraz-dava-dilekcesi-ornegi-1163-16/'),
('Miras Hukuku', 'Mirasın Reddi Dilekçesi Örneği (2026) — TMK m.605 ve Üç Aylık Süre', 'https://hukukcularevi.com/mirasin-reddi-dilekcesi-ornegi/'),
('Miras Hukuku', 'Veraset İlamı Talep Dilekçesi Örneği (2026): Noter mi, Mahkeme mi?', 'https://hukukcularevi.com/veraset-ilami-talep-dilekcesi-ornegi/'),
('Miras Hukuku', 'Ortaklığın Giderilmesi (İzale-i Şuyu) Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/ortakligin-giderilmesi-izale-i-suyu-dava-dilekcesi-ornegi/'),
('Miras Hukuku', 'Muris Muvazaası Tapu İptali ve Tescil Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/muris-muvazaasi-tapu-iptali-ve-tescil-dava-dilekcesi-ornegi/'),
('Miras Hukuku', 'Tenkis Dava Dilekçesi Örneği (2026) — TMK m.560 ve 1 Yıl / 10 Yıl', 'https://hukukcularevi.com/tenkis-dava-dilekcesi-ornegi/'),
('Miras Hukuku', 'Gaiplik Kararı Talebi Dilekçesi Örneği (2026) — TMK m.32 ve 1 Yıl / 5 Yıl', 'https://hukukcularevi.com/gaiplik-karari-talebi-dilekcesi-ornegi-tmk-32/'),
('Miras Hukuku', 'Vasiyetnamenin İptali Dava Dilekçesi Örneği (2026) — TMK m.557 ve 1 Yıl', 'https://hukukcularevi.com/vasiyetnamenin-iptali-dava-dilekcesi-ornegi-tmk-557/'),
('Miras Hukuku', 'Mirasta Denkleştirme (İade) Dava Dilekçesi Örneği (2026) — TMK m.669', 'https://hukukcularevi.com/mirasta-denklestirme-iade-dava-dilekcesi-ornegi-tmk-669/'),
('Miras Hukuku', 'Aile Konutunun Sağ Kalan Eşe Özgülenmesi Dava Dilekçesi Örneği (2026) — TMK m.65', 'https://hukukcularevi.com/aile-konutunun-sag-kalan-ese-ozgulenmesi-dava-dilekcesi-ornegi-tmk-652/'),
('Miras Hukuku', 'Ehil Mirasçılığın Tespiti ve Tarım Arazisinin Devri Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/ehil-mirasciligin-tespiti-ve-tarim-arazisinin-devri-dava-dilekcesi-ornegi-5403/'),
('Miras Hukuku', 'Terekenin Tespiti ve Resmî Defter Tutma Talebi Dilekçesi Örneği (2026) — TMK m.5', 'https://hukukcularevi.com/terekenin-tespiti-ve-resmi-defter-tutma-talebi-dilekcesi-ornegi-tmk-619/'),
('Miras Hukuku', 'Mirasçılıktan Çıkarmanın (Iskatın) İptali Dava Dilekçesi Örneği (2026) — TMK m.5', 'https://hukukcularevi.com/mirasciliktan-cikarmanin-iskat-iptali-dava-dilekcesi-ornegi-tmk-510/'),
('Miras Hukuku', 'Miras Ortaklığına Temsilci Atanması Talebi Dilekçesi Örneği (2026) — TMK m.640/3', 'https://hukukcularevi.com/miras-ortakligina-temsilci-atanmasi-talebi-dilekcesi-ornegi-tmk-640/'),
('Miras Hukuku', 'Vasiyetnamenin Tenfizi (Yerine Getirilmesi) Dava Dilekçesi Örneği (2026) — TMK m', 'https://hukukcularevi.com/vasiyetnamenin-tenfizi-yerine-getirilmesi-dava-dilekcesi-ornegi-tmk-600/'),
('Miras Hukuku', 'Miras Payının Devri (Temliki) ve Payın Verilmesi Dava Dilekçesi Örneği (2026) —', 'https://hukukcularevi.com/miras-payinin-devri-temliki-dava-dilekcesi-ornegi-tmk-677/'),
('Miras Hukuku', 'Mirastan Feragat Sözleşmesinin Hükümsüzlüğü Dava Dilekçesi Örneği (2026) — TMK m', 'https://hukukcularevi.com/mirastan-feragat-sozlesmesinin-hukumsuzlugu-dava-dilekcesi-ornegi-tmk-528/'),
('Miras Hukuku', 'Miras Sebebiyle İstihkak Dava Dilekçesi Örneği (2026) — TMK m.637-639', 'https://hukukcularevi.com/miras-sebebiyle-istihkak-dava-dilekcesi-ornegi-tmk-637/'),
('Miras Hukuku', 'Vasiyetnamenin Açılması ve Okunması Talebi Dilekçesi Örneği (2026) — TMK m.595-5', 'https://hukukcularevi.com/vasiyetnamenin-acilmasi-ve-okunmasi-talebi-dilekcesi-ornegi-tmk-595/'),
('Miras Hukuku', 'Terekenin Resmî Tasfiyesi Talebi Dilekçesi Örneği (2026) — TMK m.632-636', 'https://hukukcularevi.com/terekenin-resmi-tasfiyesi-talebi-dilekcesi-ornegi-tmk-632/'),
('Tüketici Hukuku', 'Tüketici Hakem Heyeti Başvuru Dilekçesi Örneği (2026) — 186.000 TL Sınırı', 'https://hukukcularevi.com/tuketici-hakem-heyeti-basvuru-dilekcesi-ornegi/'),
('Tüketici Hukuku', 'Tüketici Mahkemesi Dava Dilekçesi Örneği (2026) — Arabuluculuk Şartı ve Parasal', 'https://hukukcularevi.com/tuketici-mahkemesi-dava-dilekcesi-ornegi/'),
('Tüketici Hukuku', 'Cayma Hakkı ve Bedel İadesi Başvuru Dilekçesi Örneği (2026) — TKHK m.48', 'https://hukukcularevi.com/cayma-hakki-bedel-iadesi-basvuru-dilekcesi-ornegi-tkhk-48/'),
('Tüketici Hukuku', 'Abonelik Feshi ve Haksız Cayma Bedeli Başvuru Dilekçesi Örneği (2026) — TKHK m.5', 'https://hukukcularevi.com/abonelik-feshi-cayma-bedeli-itiraz-basvuru-dilekcesi-ornegi-tkhk-52/'),
('Tüketici Hukuku', 'Kartın Haksız Kullanımı ve İade Başvuru Dilekçesi Örneği (2026) — 5464 s.K. m.12', 'https://hukukcularevi.com/kartin-haksiz-kullanimi-iade-basvuru-dilekcesi-ornegi-5464-12/'),
('İş Hukuku', 'İstifa Dilekçesinin İradeyi Sakatlayan Hâller (Baskı, Hile, Korkutma)', 'https://hukukcularevi.com/istifa-dilekcesinin-iradeyi-sakatlayan-haller-baski-hile-korkutma/'),
('İş Hukuku', 'İşe Girerken Boş Senet veya İstifa Dilekçesi İmzalattılar', 'https://hukukcularevi.com/ise-girerken-bos-senet-veya-istifa-dilekcesi-imzalattilar/'),
('İş Hukuku', 'İşe İade Dava Dilekçesi Örneği (2026) — 1 Ay + 2 Hafta Kuralı', 'https://hukukcularevi.com/ise-iade-dava-dilekcesi-ornegi/'),
('İş Hukuku', 'Kıdem-İhbar Tazminatı ve İşçilik Alacakları Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/kidem-ihbar-tazminati-iscilik-alacaklari-dava-dilekcesi-ornegi/'),
('İş Hukuku', 'İşçinin Haklı Nedenle Fesih İhtarnamesi Örneği (2026) — 4857 m.24 ve 6 İş Günü', 'https://hukukcularevi.com/hakli-nedenle-fesih-ihtarnamesi-ornegi-isci/'),
('İş Hukuku', 'İş Kazası Maddi ve Manevi Tazminat Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/is-kazasi-tazminat-dava-dilekcesi-ornegi/'),
('İş Hukuku', 'Hizmet Tespit Dava Dilekçesi Örneği (2026) — 5510 m.86/9 ve 5 Yıl', 'https://hukukcularevi.com/hizmet-tespit-dava-dilekcesi-ornegi/'),
('İş Hukuku', 'Mobbing Dava Dilekçesi Örneği (2026) — TBK m.417 ve Yaklaşık İspat', 'https://hukukcularevi.com/mobbing-manevi-tazminat-dava-dilekcesi-ornegi/'),
('İş Hukuku', 'Alt İşveren Muvazaasının Tespiti Dava Dilekçesi Örneği (2026) — 4857 s.K. m.2', 'https://hukukcularevi.com/alt-isveren-muvazaasinin-tespiti-dava-dilekcesi-ornegi-4857-2/'),
('İş Hukuku', 'Sendikal Tazminat Dava Dilekçesi Örneği (2026) — 6356 s.K. m.25', 'https://hukukcularevi.com/sendikal-tazminat-dava-dilekcesi-ornegi-6356-25/'),
('İş Hukuku', 'Bakiye Süre Ücreti Dava Dilekçesi Örneği (2026) — TBK m.438', 'https://hukukcularevi.com/bakiye-sure-ucreti-dava-dilekcesi-ornegi-tbk-438/'),
('İş Hukuku', 'Rekabet Yasağının Geçersizliğinin Tespiti Dava Dilekçesi Örneği (2026) — TBK m.4', 'https://hukukcularevi.com/rekabet-yasaginin-gecersizligi-tespit-dava-dilekcesi-ornegi-tbk-444/'),
('İdare Hukuku', 'SPK Kararına Karşı İptal Davası Dilekçesi Örneği (2026) — İşlem Yasağı, Erişim E', 'https://hukukcularevi.com/spk-kararina-karsi-iptal-davasi-dilekcesi-ornegi-islem-yasagi-erisim-engeli-lisans-iptali-idari-para-cezasi-yurutmenin-durdurulmasi-iyuk-3-7-11-27/'),
('İdare Hukuku', 'SPK''ya Karşı Tam Yargı (Tazminat) Dava Dilekçesi Örneği (2026) — Fon Mağdurları,', 'https://hukukcularevi.com/spkya-karsi-tam-yargi-dava-dilekcesi-ornegi-fon-magduru-iyuk-12-3-7-20-spkn-133-134/'),
('İdare Hukuku', 'SPK Fon Tasfiye Kararına Karşı İptal Davası Dilekçesi (2026) — Yürütmenin Durdur', 'https://hukukcularevi.com/spk-fon-tasfiye-karari-iptal-davasi-yatirimci-yurutmenin-durdurulmasi-iyuk-7-11-27-spkn-134/'),
('İdare Hukuku', 'İdari İşlemin İptali Dava Dilekçesi Örneği (2026) — İYUK m.3 ve 60 Gün', 'https://hukukcularevi.com/idari-islemin-iptali-dava-dilekcesi-ornegi/'),
('İdare Hukuku', 'Tam Yargı (İdari Tazminat) Davası Dilekçesi Örneği (2026) — İYUK m.12 ve 13', 'https://hukukcularevi.com/tam-yargi-davasi-dilekcesi-ornegi/'),
('İdare Hukuku', 'Disiplin Cezasına İtiraz Dilekçesi Örneği (2026) — 657 m.135 ve 7 Gün', 'https://hukukcularevi.com/disiplin-cezasina-itiraz-dilekcesi-ornegi-657/'),
('İdare Hukuku', 'Güvenlik Soruşturması İptal Dava Dilekçesi Örneği (2026) — 7315 ve 60 Gün', 'https://hukukcularevi.com/guvenlik-sorusturmasi-iptal-dava-dilekcesi-ornegi-7315/'),
('İdare Hukuku', 'Yapı Tatil Tutanağı İptal Dava Dilekçesi Örneği (2026) — İmar m.32 ve 60 Gün', 'https://hukukcularevi.com/yapi-tatil-tutanagi-iptal-dava-dilekcesi-ornegi-imar-32/'),
('İdare Hukuku', 'Naklen Atama İptali Dava Dilekçesi Örneği (2026) — 657 s.K. m.76', 'https://hukukcularevi.com/naklen-atama-iptal-dava-dilekcesi-ornegi-657-76/'),
('İdare Hukuku', 'Öğrenci Disiplin Cezasına İtiraz ve İptal Dava Dilekçesi Örneği (2026) — 2547 s.', 'https://hukukcularevi.com/ogrenci-disiplin-cezasina-itiraz-ve-iptal-dava-dilekcesi-ornegi-2547/'),
('İdare Hukuku', 'Askerlik Sağlık Raporuna İtiraz Dilekçesi Örneği (2026) — 7179 s.K. m.16', 'https://hukukcularevi.com/askerlik-saglik-raporuna-itiraz-dilekcesi-ornegi-7179/'),
('İdare Hukuku', 'Yürütmenin Durdurulması Kararına İtiraz Dilekçesi Örneği (2026) — İYUK m.27 ve Y', 'https://hukukcularevi.com/yurutmenin-durdurulmasi-karari-itiraz-dilekcesi-ornegi-iyuk-27/'),
('İdare Hukuku', 'İdari Yargıda İstinaf Dilekçesi Örneği (2026) — İYUK m.45 ve Otuz Gün', 'https://hukukcularevi.com/idari-yargida-istinaf-dilekcesi-ornegi-iyuk-45/'),
('İdare Hukuku', 'Harcamalara Katılma Payı Tahakkukunun İptali Dava Dilekçesi Örneği (2026) — 2464', 'https://hukukcularevi.com/harcamalara-katilma-payi-iptal-dava-dilekcesi-ornegi-2464/'),
('İdare Hukuku', 'Teknik Altyapı Bedelinin İptali ve İadesi Dava Dilekçesi Örneği (2026) — İmar Ka', 'https://hukukcularevi.com/teknik-altyapi-bedeli-iptal-iade-dava-dilekcesi-ornegi-imar-23/'),
('İdare Hukuku', 'Otopark Bedelinin İptali ve İadesi Dava Dilekçesi Örneği (2026) — Otopark Yönetm', 'https://hukukcularevi.com/otopark-bedeli-iptal-iade-dava-dilekcesi-ornegi/'),
('İdare Hukuku', 'Değer Artış Payına İtiraz ve İptal Dava Dilekçesi Örneği (2026) — İmar Kanunu Ek', 'https://hukukcularevi.com/deger-artis-payi-itiraz-iptal-dava-dilekcesi-ornegi-imar-ek-8/'),
('İdare Hukuku', 'Kot Tespitine İtiraz ve İptal Dava Dilekçesi Örneği (2026) — Kotlandırma ve Suba', 'https://hukukcularevi.com/kot-tespitine-itiraz-iptal-dava-dilekcesi-ornegi/'),
('İdare Hukuku', 'Kıyı Kenar Çizgisine İtiraz ve İptal Dava Dilekçesi Örneği (2026) — 3621 m.9', 'https://hukukcularevi.com/kiyi-kenar-cizgisi-itiraz-iptal-dava-dilekcesi-ornegi-3621/'),
('İdare Hukuku', 'İmar Planı Değişikliği Talebi ve Reddine Karşı Dava Dilekçesi Örneği (2026) — İm', 'https://hukukcularevi.com/imar-plani-degisikligi-talebi-basvuru-dava-dilekcesi-ornegi/'),
('İdare Hukuku', 'İdari Yargıda Temyiz Dilekçesi Örneği (2026) — İYUK m.46 (Danıştay)', 'https://hukukcularevi.com/idari-yargida-temyiz-dilekcesi-ornegi-iyuk-46/'),
('Vergi Hukuku', 'Vergi Mahkemesi Dava Dilekçesi Örneği (2026) — İhbarnameye Karşı 30 Gün', 'https://hukukcularevi.com/vergi-mahkemesi-dava-dilekcesi-ornegi/'),
('Vergi Hukuku', 'Ödeme Emrine İtiraz Dava Dilekçesi Örneği (2026) — 6183 m.58 ve 15 Gün', 'https://hukukcularevi.com/odeme-emrine-itiraz-dava-dilekcesi-ornegi-6183/'),
('Vergi Hukuku', 'Vergi Hatası Düzeltme ve Şikâyet Dilekçesi Örneği (2026) — VUK m.124', 'https://hukukcularevi.com/vergi-hatasi-duzeltme-sikayet-dilekcesi-ornegi-vuk-124/'),
('Trafik ve Tazminat Hukuku', 'Maluliyet Raporuna İtiraz ve Adli Tıp''a Sevk Talebi Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/maluliyet-raporuna-itiraz-ve-adli-tipa-sevk-talebi-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Islah Dilekçesi Örneği (2026) — HMK m. 176', 'https://hukukcularevi.com/islah-dilekcesi-ornegi-hmk-176-tazminat-davasi/'),
('Trafik ve Tazminat Hukuku', 'Talep Artırım Dilekçesi Örneği (2026) — HMK m. 109/4', 'https://hukukcularevi.com/talep-artirim-dilekcesi-ornegi-hmk-109-4-kismi-dava/'),
('Trafik ve Tazminat Hukuku', 'Sigorta Hakem Kararına İtiraz Dilekçesi Örneği (2026) — 10 Gün', 'https://hukukcularevi.com/sigorta-hakem-kararina-itiraz-dilekcesi-ornegi-5684-30/'),
('Trafik ve Tazminat Hukuku', 'İbranameye Rağmen Bakiye Tazminat Dava Dilekçesi Örneği (2026) — KTK m. 111', 'https://hukukcularevi.com/ibranameye-ragmen-bakiye-tazminat-dava-dilekcesi-ornegi-ktk-111/'),
('Trafik ve Tazminat Hukuku', 'Trafik Kazasında Manevi Tazminat Dava Dilekçesi Örneği (2026) — TBK m. 56', 'https://hukukcularevi.com/trafik-kazasinda-manevi-tazminat-dava-dilekcesi-ornegi-tbk-56/'),
('Trafik ve Tazminat Hukuku', 'Zamanaşımı Def''ine Cevap Dilekçesi Örneği (2026) — KTK m. 109', 'https://hukukcularevi.com/zamanasimi-define-cevap-dilekcesi-ornegi-ktk-109-trafik-kazasi/'),
('Trafik ve Tazminat Hukuku', 'Bakıcı Gideri ve Sürekli Bakım Tazminatı Dava Dilekçesi Örneği (2026) — TBK m. 5', 'https://hukukcularevi.com/bakici-gideri-ve-surekli-bakim-tazminati-dava-dilekcesi-ornegi-tbk-54/'),
('Trafik ve Tazminat Hukuku', 'İMM Poliçesine Başvuru ve Dava Dilekçesi Örneği (2026) — İhtiyari Mali Mesuliyet', 'https://hukukcularevi.com/imm-policesine-basvuru-ve-dava-dilekcesi-ornegi-ihtiyari-mali-mesuliyet/'),
('Trafik ve Tazminat Hukuku', 'Koltuk Ferdi Kaza Sigortası Tazminat Talebi Dilekçesi Örneği (2026) — Otobüs, Mi', 'https://hukukcularevi.com/koltuk-ferdi-kaza-sigortasi-tazminat-talebi-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'SGK Rücu Davasına Cevap Dilekçesi Örneği (2026) — 5510 s.K. m. 21 ve m. 39', 'https://hukukcularevi.com/sgk-rucu-davasina-cevap-dilekcesi-ornegi-5510-21-39/'),
('Trafik ve Tazminat Hukuku', 'Trafik Kazası Tazminat Davasına Cevap Dilekçesi Örneği (2026) — Davalı Sürücü ve', 'https://hukukcularevi.com/trafik-kazasi-tazminat-davasina-cevap-dilekcesi-ornegi-davali-surucu-isleten/'),
('Trafik ve Tazminat Hukuku', 'Trafik Kazası Tazminat Davasında İstinaf Dilekçesi Örneği (2026) — HMK m. 341 ve', 'https://hukukcularevi.com/trafik-kazasi-tazminat-davasinda-istinaf-dilekcesi-ornegi-hmk-341-345/'),
('Trafik ve Tazminat Hukuku', 'Müterafik Kusur İndirimine Karşı Beyan Dilekçesi Örneği (2026) — Yaya, Motosikle', 'https://hukukcularevi.com/muterafik-kusur-indirimine-karsi-beyan-dilekcesi-ornegi-yaya-motosiklet-kask/'),
('Trafik ve Tazminat Hukuku', 'Çocuk Mağdurda Trafik Kazası Tazminat Dava Dilekçesi Örneği (2026) — ÇÖZGER ve E', 'https://hukukcularevi.com/cocuk-magdur-trafik-kazasi-tazminat-dava-dilekcesi-ornegi-cozger/'),
('Trafik ve Tazminat Hukuku', 'Trafik Kazası Aynı Zamanda İş Kazası ise Dava Dilekçesi Örneği (2026) — İki Ayrı', 'https://hukukcularevi.com/trafik-kazasi-ayni-zamanda-is-kazasi-ise-dava-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Hatır Taşımasında Yolcunun Tazminat Dava Dilekçesi Örneği (2026) — KTK m. 87', 'https://hukukcularevi.com/hatir-tasimasinda-yolcunun-tazminat-dava-dilekcesi-ornegi-ktk-87/'),
('Trafik ve Tazminat Hukuku', 'Trafik Kazası Tazminatında Görev ve Yetki İtirazına Cevap Dilekçesi Örneği (2026', 'https://hukukcularevi.com/trafik-kazasi-tazminatinda-gorev-ve-yetki-itirazina-cevap-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Cenaze, Defin Giderleri ve Ölüme Bağlı Tazminat Dava Dilekçesi Örneği (2026) — T', 'https://hukukcularevi.com/cenaze-defin-giderleri-ve-olume-bagli-tazminat-dava-dilekcesi-ornegi-tbk-53/'),
('Trafik ve Tazminat Hukuku', 'Trafik Kazası Tazminatında Temyiz Dilekçesi Örneği (2026) — HMK m. 361 ve 371', 'https://hukukcularevi.com/trafik-kazasi-tazminatinda-temyiz-dilekcesi-ornegi-hmk-361-371/'),
('Trafik ve Tazminat Hukuku', 'Uzlaştırma Teklifine Cevap ve Tazminat Haklarının Saklı Tutulması Dilekçesi Örne', 'https://hukukcularevi.com/uzlastirma-teklifine-cevap-ve-tazminat-haklarinin-saklanmasi-dilekcesi-ornegi-cmk-253/'),
('Trafik ve Tazminat Hukuku', 'Tazminat Alacağı İçin İhtiyati Haciz Talebi Dilekçesi Örneği (2026) — İİK m. 257', 'https://hukukcularevi.com/tazminat-alacagi-icin-ihtiyati-haciz-talebi-dilekcesi-ornegi-iik-257/'),
('Trafik ve Tazminat Hukuku', 'Zincirleme Kazada Müteselsil Sorumluluk ve Rücu Dava Dilekçesi Örneği (2026) — K', 'https://hukukcularevi.com/zincirleme-kazada-muteselsil-sorumluluk-ve-rucu-dava-dilekcesi-ornegi-ktk-88/'),
('Trafik ve Tazminat Hukuku', 'Yurt Dışında Yaşayan Mağdurun Trafik Kazası Tazminat Dava Dilekçesi Örneği (2026', 'https://hukukcularevi.com/yurt-disinda-yasayan-magdurun-trafik-kazasi-tazminat-dava-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Araç Mahrumiyet Bedeli (İkame Araç) Dava Dilekçesi Örneği (2026) — Sigortadan İs', 'https://hukukcularevi.com/arac-mahrumiyet-bedeli-ikame-arac-dava-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Trafik Kazası Tazminatında AYM Bireysel Başvuru Dilekçesi Örneği (2026) — 6216 s', 'https://hukukcularevi.com/trafik-kazasi-tazminatinda-aym-bireysel-basvuru-dilekcesi-ornegi-6216/'),
('Trafik ve Tazminat Hukuku', 'Kaza Tespit Tutanağına İtiraz ve Aksinin İspatı Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/kaza-tespit-tutanagina-itiraz-ve-aksinin-ispati-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Tedavi ve Yaşam Boyu Giderler Talebi Dilekçesi Örneği (2026) — TBK m. 54, KTK m.', 'https://hukukcularevi.com/tedavi-ve-yasam-boyu-giderler-talebi-dilekcesi-ornegi-tbk-54-ktk-98/'),
('Trafik ve Tazminat Hukuku', 'Ağır Maluliyette Vasi ve Kayyım Atanması Talebi Dilekçesi Örneği (2026) — TMK m.', 'https://hukukcularevi.com/agir-maluliyette-vasi-ve-kayyim-atanmasi-talebi-dilekcesi-ornegi-tmk-405/'),
('Trafik ve Tazminat Hukuku', 'Tazminat Davasında Adli Yardım Talebi Dilekçesi Örneği (2026) — HMK m. 334', 'https://hukukcularevi.com/tazminat-davasinda-adli-yardim-talebi-dilekcesi-ornegi-hmk-334/'),
('Trafik ve Tazminat Hukuku', 'Uzman Görüşü Sunulması Dilekçesi Örneği (2026) — HMK m. 293, Tazminat Davası', 'https://hukukcularevi.com/uzman-gorusu-sunulmasi-dilekcesi-ornegi-hmk-293-tazminat-davasi/'),
('Trafik ve Tazminat Hukuku', 'Yabancı Plakalı Araç Kazasında Tazminat Dilekçesi Örneği (2026) — Yeşil Kart ve', 'https://hukukcularevi.com/yabanci-plakali-arac-kazasinda-tazminat-yesil-kart-ve-tmtb-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Ölümlü Trafik Kazasında Soruşturma: Delil Talebi ve Takipsizliğe İtiraz Dilekçes', 'https://hukukcularevi.com/olumlu-trafik-kazasinda-sorusturma-delil-talebi-ve-takipsizlige-itiraz-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Tazminat İlamının İcrası: İlamlı Takip Dilekçesi Örneği (2026) — İİK m. 32', 'https://hukukcularevi.com/tazminat-ilaminin-icrasi-ilamli-takip-dilekcesi-ornegi-iik-32/'),
('Trafik ve Tazminat Hukuku', 'Tehiri İcra (İcranın Geri Bırakılması) Talebi Dilekçesi Örneği (2026) — İİK m. 3', 'https://hukukcularevi.com/tehiri-icra-icranin-geri-birakilmasi-talebi-dilekcesi-ornegi-iik-36/'),
('Trafik ve Tazminat Hukuku', 'Sürekli İş Göremezlik Geliri Başvurusu ve İtiraz Dilekçesi Örneği (2026) — 5510', 'https://hukukcularevi.com/surekli-is-goremezlik-geliri-basvurusu-ve-itiraz-dilekcesi-ornegi-5510-19/'),
('Trafik ve Tazminat Hukuku', 'Ölüm Geliri Başvurusu ve Hak Sahipliği İtiraz Dilekçesi Örneği (2026) — 5510 s.K', 'https://hukukcularevi.com/olum-geliri-basvurusu-ve-hak-sahipligi-itiraz-dilekcesi-ornegi-5510-20-34/'),
('Trafik ve Tazminat Hukuku', 'Bilirkişinin Reddi Talebi Dilekçesi Örneği (2026) — HMK m. 272 ve 273', 'https://hukukcularevi.com/bilirkisinin-reddi-talebi-dilekcesi-ornegi-hmk-272-273/'),
('Trafik ve Tazminat Hukuku', 'Aracın Devrinin Önlenmesi ve İhtiyati Tedbir Talebi Dilekçesi Örneği (2026) — HM', 'https://hukukcularevi.com/aracin-devrinin-onlenmesi-ihtiyati-tedbir-talebi-dilekcesi-ornegi-hmk-389/'),
('Trafik ve Tazminat Hukuku', 'Çoklu Mağdurlu Kazada Garame: Başvuru ve Dava Dilekçesi Örneği (2026) — KTK m. 9', 'https://hukukcularevi.com/coklu-magdurlu-kazada-garame-basvuru-ve-dava-dilekcesi-ornegi-ktk-96/'),
('Trafik ve Tazminat Hukuku', 'Ev Hanımı, Öğrenci ve İşsiz Mağdurun Tazminat Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/ev-hanimi-ogrenci-issiz-magdurun-tazminat-dava-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Keşif ve Olay Yerinde İnceleme Talebi Dilekçesi Örneği (2026) — HMK m. 288', 'https://hukukcularevi.com/kesif-ve-olay-yerinde-inceleme-talebi-dilekcesi-ornegi-hmk-288/'),
('Trafik ve Tazminat Hukuku', 'Engelli Sağlık Kurulu Raporuna İtiraz Dilekçesi Örneği (2026) — 30 Gün ve Hakem', 'https://hukukcularevi.com/engelli-saglik-kurulu-raporuna-itiraz-dilekcesi-ornegi-30-gun-hakem-hastane/'),
('Trafik ve Tazminat Hukuku', 'Elektrikli Scooter ve Bisiklet Kazasında Tazminat Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/elektrikli-scooter-ve-bisiklet-kazasinda-tazminat-dava-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Çalıntı Araç Kazasında Tazminat Dava Dilekçesi Örneği (2026) — KTK m. 107', 'https://hukukcularevi.com/calinti-arac-kazasinda-tazminat-dava-dilekcesi-ornegi-ktk-107/'),
('Trafik ve Tazminat Hukuku', 'Kiralık Araç Kazasında Tazminat ve İşleten Sıfatı Dilekçesi Örneği (2026) — KTK', 'https://hukukcularevi.com/kiralik-arac-kazasinda-tazminat-ve-isleten-sifati-dilekcesi-ornegi-ktk-3/'),
('Trafik ve Tazminat Hukuku', 'Okul Servisi Kazasında Tazminat Dava Dilekçesi Örneği (2026) — Rehber Personel v', 'https://hukukcularevi.com/okul-servisi-kazasinda-tazminat-dava-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Davanın İhbarı ve Fer''î Müdahale Dilekçesi Örneği (2026) — HMK m. 61-67', 'https://hukukcularevi.com/davanin-ihbari-ve-feri-mudahale-dilekcesi-ornegi-hmk-61-65-tazminat/'),
('Trafik ve Tazminat Hukuku', 'Görev Sırasındaki Kazada İşverenin Sorumluluğu Dava Dilekçesi Örneği (2026) — TB', 'https://hukukcularevi.com/gorev-sirasindaki-kazada-isverenin-sorumlulugu-dava-dilekcesi-ornegi-tbk-66/'),
('Trafik ve Tazminat Hukuku', 'Yola Çıkan Hayvan Kazasında Tazminat Dava Dilekçesi Örneği (2026) — TBK m. 67, K', 'https://hukukcularevi.com/yola-cikan-hayvan-kazasinda-tazminat-dava-dilekcesi-ornegi-tbk-67-ktk-69/'),
('Trafik ve Tazminat Hukuku', 'Hasarsızlık İndirimi (Basamak) Düzeltme ve İtiraz Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/hasarsizlik-indirimi-basamak-duzeltme-ve-itiraz-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Çarpıp Kaçan Sürücü: Mağdurun Yapacakları ve Dilekçe Örnekleri (2026) — KTK m. 8', 'https://hukukcularevi.com/carpip-kacan-surucu-magdurun-yapacaklari-dilekce-ornegi-ktk-81-tck-98/'),
('Trafik ve Tazminat Hukuku', 'Traktör ve İş Makinesi Kazasında Tazminat Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/traktor-ve-is-makinesi-kazasinda-tazminat-dava-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'İş Makinesi Tescili, Plakası ve Devri Rehberi (2026) — KTK m. 22', 'https://hukukcularevi.com/is-makinesi-tescili-plakasi-ve-devri-rehberi-ktk-22/'),
('Trafik ve Tazminat Hukuku', 'İş Makinesi Operatör Belgesi, G Sınıfı ve Yetkisiz Kullanım Rehberi (2026)', 'https://hukukcularevi.com/is-makinesi-operator-belgesi-g-sinifi-ve-yetkisiz-kullanim-rehberi/'),
('Trafik ve Tazminat Hukuku', 'İş Makinesiyle İş Kazası ve İşverenin Sorumluluğu Rehberi (2026) — 6331 s.K., TB', 'https://hukukcularevi.com/is-makinesiyle-is-kazasi-ve-isverenin-sorumlulugu-rehberi-6331-tbk-417/'),
('Trafik ve Tazminat Hukuku', 'Operatörlü ve Operatörsüz İş Makinesi Kiralamada Sorumluluk Rehberi (2026)', 'https://hukukcularevi.com/operatorlu-operatorsuz-is-makinesi-kiralama-ve-sorumluluk-rehberi/'),
('Trafik ve Tazminat Hukuku', 'İkinci El İş Makinesi Alımında Ayıp ve Saat Sayacı Hilesi Rehberi (2026) — TTK m', 'https://hukukcularevi.com/ikinci-el-is-makinesi-aliminda-ayip-ve-saat-sayaci-hilesi-rehberi/'),
('Trafik ve Tazminat Hukuku', 'İş Makinesi Sigortaları: Makine Kırılması, Geniş Kasko ve Hırsızlık Rehberi (202', 'https://hukukcularevi.com/is-makinesi-sigortalari-makine-kirilmasi-genis-kasko-ve-hirsizlik-rehberi/'),
('Trafik ve Tazminat Hukuku', 'İş Makinesinde Finansal Kiralama (Leasing) Rehberi (2026) — 6361 sayılı Kanun', 'https://hukukcularevi.com/is-makinesinde-finansal-kiralama-leasing-rehberi-6361/'),
('Trafik ve Tazminat Hukuku', 'İş Makinesinin Haczi, Rehni ve İstihkak Rehberi (2026) — İİK m. 82, 96', 'https://hukukcularevi.com/is-makinesinin-haczi-rehni-ve-istihkak-rehberi-iik-82-96/'),
('Trafik ve Tazminat Hukuku', 'Kazı Sırasında Doğalgaz, Elektrik ve Su Hattı Hasarı: Sorumluluk Rehberi (2026)', 'https://hukukcularevi.com/kazi-sirasinda-dogalgaz-elektrik-su-hatti-hasari-sorumluluk-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Malpraktis Davası: Kamu mu Özel mi, Hangi Mahkeme, Hangi Süre? (2026)', 'https://hukukcularevi.com/malpraktis-davasi-kamu-mu-ozel-mi-hangi-mahkeme-hangi-sure-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Aydınlatılmış Onam: İspat Yükü ve Geçerlilik Şartları Rehberi (2026)', 'https://hukukcularevi.com/aydinlatilmis-onam-ispat-yuku-ve-gecerlilik-sartlari-rehberi-malpraktis/'),
('Trafik ve Tazminat Hukuku', 'Komplikasyon mu, Malpraktis mi? Ayrım ve Komplikasyon Yönetimi Rehberi (2026)', 'https://hukukcularevi.com/komplikasyon-mu-malpraktis-mi-ayrim-ve-komplikasyon-yonetimi-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Doğum Malpraktisi: Serebral Palsi ve Yenidoğan Hasarları Rehberi (2026)', 'https://hukukcularevi.com/dogum-malpraktisi-serebral-palsi-ve-yenidogan-hasarlari-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Estetik Ameliyat: Eser Sözleşmesi ve Sonuç Sorumluluğu Rehberi (2026)', 'https://hukukcularevi.com/estetik-ameliyat-eser-sozlesmesi-ve-sonuc-sorumlulugu-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Malpraktiste Adli Tıp Raporu ve İtiraz Rehberi (2026) — HMK m. 281, 293', 'https://hukukcularevi.com/malpraktiste-adli-tip-raporu-ve-itiraz-rehberi-hmk-281-293/'),
('Trafik ve Tazminat Hukuku', 'Ölümle Sonuçlanan Malpraktis: Tazminat ve Ceza Yolu Rehberi (2026)', 'https://hukukcularevi.com/olumle-sonuclanan-malpraktis-tazminat-ve-ceza-yolu-rehberi-msk/'),
('Trafik ve Tazminat Hukuku', 'Hasta Dosyası Nasıl Alınır? Malpraktiste Delil Toplama Rehberi (2026)', 'https://hukukcularevi.com/hasta-dosyasi-nasil-alinir-ve-delil-toplama-rehberi-malpraktis/'),
('Trafik ve Tazminat Hukuku', 'Diş Hekimliğinde Malpraktis: İmplant, Protez ve Çekim Rehberi (2026)', 'https://hukukcularevi.com/dis-hekimliginde-malpraktis-implant-protez-ve-cekim-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Hekim Zorunlu Mesleki Sorumluluk Sigortası ve Doğrudan Dava Rehberi (2026)', 'https://hukukcularevi.com/hekim-zorunlu-mesleki-sorumluluk-sigortasi-ve-dogrudan-dava-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Hastane Enfeksiyonu ve Organizasyon Kusuru Tazminat Rehberi (2026)', 'https://hukukcularevi.com/hastane-enfeksiyonu-ve-organizasyon-kusuru-tazminat-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Anestezi Malpraktisi: Ayrı Onam, Preoperatif Değerlendirme ve Derlenme (2026)', 'https://hukukcularevi.com/anestezi-malpraktisi-ayri-onam-preoperatif-degerlendirme-ve-derlenme/'),
('Trafik ve Tazminat Hukuku', 'Acil Serviste Malpraktis: Triyaj, Stabilizasyon ve Sevk Rehberi (2026)', 'https://hukukcularevi.com/acil-serviste-malpraktis-triyaj-stabilizasyon-ve-sevk-rehberi/'),
('Trafik ve Tazminat Hukuku', 'İlaç Uygulama ve Reçete Hataları: Malpraktis Sorumluluk Rehberi (2026)', 'https://hukukcularevi.com/ilac-uygulama-ve-recete-hatalari-malpraktis-sorumluluk-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Yanlış Taraf Cerrahisi ve Ameliyatta Yabancı Cisim Unutulması Rehberi (2026)', 'https://hukukcularevi.com/yanlis-taraf-cerrahisi-ve-ameliyatta-yabanci-cisim-unutulmasi-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Kanserde Tanı Gecikmesi ve Sonuç Takip Zinciri: Tazminat Rehberi (2026)', 'https://hukukcularevi.com/kanserde-tani-gecikmesi-ve-sonuc-takip-zinciri-tazminat-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Ortopedi Malpraktisi: Kompartman Sendromu, Alçı ve Kırık Tanısı Rehberi (2026)', 'https://hukukcularevi.com/ortopedi-malpraktisi-kompartman-sendromu-alci-ve-kirik-tanisi-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Safra Kesesi Ameliyatında Safra Yolu Yaralanması: Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/safra-kesesi-ameliyatinda-safra-yolu-yaralanmasi-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Göz Hastalıklarında Malpraktis: ROP, Katarakt ve Lazer Rehberi (2026)', 'https://hukukcularevi.com/goz-hastaliklarinda-malpraktis-rop-katarakt-ve-lazer-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Kalp Krizi Tanısının Atlanması: EKG, Troponin ve Gözlem Rehberi (2026)', 'https://hukukcularevi.com/kalp-krizi-tanisinin-atlanmasi-ekg-troponin-ve-gozlem-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Radyoloji ve Patoloji Rapor Hataları: Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/radyoloji-ve-patoloji-rapor-hatalari-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Saç Ekiminde Malpraktis: Yetkisiz Uygulama ve Eser Sözleşmesi Rehberi (2026)', 'https://hukukcularevi.com/sac-ekiminde-malpraktis-yetkisiz-uygulama-ve-eser-sozlesmesi-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Obezite Cerrahisinde Malpraktis: Endikasyon, Konsey ve Takip Rehberi (2026)', 'https://hukukcularevi.com/obezite-cerrahisinde-malpraktis-endikasyon-konsey-ve-takip-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Sağlık Turizminde Malpraktis: Yetki Belgesi ve Komplikasyon Sigortası (2026)', 'https://hukukcularevi.com/saglik-turizminde-malpraktis-yetki-belgesi-komplikasyon-sigortasi-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Tıbbi Kayıtların Sonradan Değiştirilmesi: Tespit ve Hukuki Sonuçları (2026)', 'https://hukukcularevi.com/tibbi-kayitlarin-sonradan-degistirilmesi-tespit-ve-hukuki-sonuclari/'),
('Trafik ve Tazminat Hukuku', 'Malpraktiste Tazminat Nasıl Hesaplanır? Kalemler ve Kusur Oranı (2026)', 'https://hukukcularevi.com/malpraktiste-tazminat-nasil-hesaplanir-kalemler-ve-kusur-orani/'),
('Trafik ve Tazminat Hukuku', 'Yenidoğan Sarılığı ve Kernikterus: Malpraktis Tazminat Rehberi (2026)', 'https://hukukcularevi.com/yenidogan-sariligi-ve-kernikterus-malpraktis-tazminat-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Sünnet Komplikasyonları ve Malpraktis: Yetki, Ortam ve Koter Rehberi (2026)', 'https://hukukcularevi.com/sunnet-komplikasyonlari-ve-malpraktis-yetki-ortam-ve-koter-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Hastanede Düşme ve Bası Yarası: Bakım Kusuru Tazminat Rehberi (2026)', 'https://hukukcularevi.com/hastanede-dusme-ve-basi-yarasi-bakim-kusuru-tazminat-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Kan Transfüzyonu Hataları ve Malpraktis: Doğrulama ve İzlem Rehberi (2026)', 'https://hukukcularevi.com/kan-transfuzyonu-hatalari-ve-malpraktis-dogrulama-izlem-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Histerektomi ve Jinekolojik Cerrahide Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/histerektomi-ve-jinekolojik-cerrahide-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Omurga ve Bel Fıtığı Cerrahisinde Malpraktis: Seviye ve Endikasyon (2026)', 'https://hukukcularevi.com/omurga-ve-bel-fitigi-cerrahisinde-malpraktis-seviye-ve-endikasyon/'),
('Trafik ve Tazminat Hukuku', 'Tüp Bebek (ÜYTE) Uygulamalarında Malpraktis ve Hukuki Sorumluluk (2026)', 'https://hukukcularevi.com/tup-bebek-uyte-uygulamalarinda-malpraktis-ve-hukuki-sorumluluk/'),
('Trafik ve Tazminat Hukuku', 'Tıbbi Cihaz Kaynaklı Zararlar ve Üreticinin Sorumluluğu Rehberi (2026)', 'https://hukukcularevi.com/tibbi-cihaz-kaynakli-zararlar-ve-ureticinin-sorumlulugu-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Hekime Rücu Davası: Husumet, Fer''î Müdahale ve Mesleki Sorumluluk Kurulu (2026)', 'https://hukukcularevi.com/hekime-rucu-davasi-husumet-feri-mudahale-ve-mesleki-sorumluluk-kurulu/'),
('Trafik ve Tazminat Hukuku', 'KBB Malpraktisi: Bademcik Kanaması, İşitme Kaybı ve Sinüs Cerrahisi (2026)', 'https://hukukcularevi.com/kbb-malpraktisi-bademcik-kanamasi-isitme-kaybi-ve-sinus-cerrahisi/'),
('Trafik ve Tazminat Hukuku', 'İnme (Felç) Tanı ve Tedavi Gecikmesi: Malpraktis Tazminat Rehberi (2026)', 'https://hukukcularevi.com/inme-felc-tani-ve-tedavi-gecikmesi-malpraktis-tazminat-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Sepsiste Tanı ve Tedavi Gecikmesi: Malpraktis Tazminat Rehberi (2026)', 'https://hukukcularevi.com/sepsiste-tani-ve-tedavi-gecikmesi-malpraktis-tazminat-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Testis Torsiyonunda Tanı Gecikmesi ve Organ Kaybı: Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/testis-torsiyonunda-tani-gecikmesi-ve-organ-kaybi-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Çocukta Menenjit Tanı Gecikmesi ve Ateşli Çocuk: Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/cocukta-menenjit-tani-gecikmesi-ve-atesli-cocuk-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Pulmoner Emboli: Tanı Gecikmesi ve Profilaksi İhmali Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/pulmoner-emboli-tani-gecikmesi-ve-profilaksi-ihmali-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Konsültasyon ve İcap Nöbeti Düzeninde Kusur: Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/konsultasyon-ve-icap-nobeti-duzeninde-kusur-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Hasta Nakli ve Ambulans Sürecinde Kusur: Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/hasta-nakli-ve-ambulans-surecinde-kusur-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Yoğun Bakım Yatağı Bulunamaması ve Yatış Gecikmesi: Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/yogun-bakim-yatagi-bulunamamasi-ve-yatis-gecikmesi-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Kolonoskopi ve Endoskopi Komplikasyonlarında Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/kolonoskopi-ve-endoskopi-komplikasyonlarinda-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Melanom ve Deri Kanserinde Tanı Gecikmesi: Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/melanom-ve-deri-kanserinde-tani-gecikmesi-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Uzaktan Sağlık Hizmeti ve Online Muayenede Sorumluluk Rehberi (2026)', 'https://hukukcularevi.com/uzaktan-saglik-hizmeti-ve-online-muayenede-sorumluluk-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Üroloji Malpraktisi: Prostat Cerrahisi ve İdrar Yolu Tıkanıklığı (2026)', 'https://hukukcularevi.com/uroloji-malpraktisi-prostat-cerrahisi-ve-idrar-yolu-tikanikligi/'),
('Trafik ve Tazminat Hukuku', 'Diyaliz Merkezlerinde Malpraktis ve Sorumluluk Rehberi (2026)', 'https://hukukcularevi.com/diyaliz-merkezlerinde-malpraktis-ve-sorumluluk-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Bypass ve Stent Kararında Malpraktis: Kalp Damar Cerrahisi Rehberi (2026)', 'https://hukukcularevi.com/bypass-ve-stent-kararinda-malpraktis-kalp-damar-cerrahisi-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Dış Gebelik (Ektopik Gebelik) Tanı Gecikmesi: Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/dis-gebelik-ektopik-gebelik-tani-gecikmesi-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Apandisit Tanı Gecikmesi ve Perforasyon: Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/apandisit-tani-gecikmesi-ve-perforasyon-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Anafilaksi ve İlaç Alerjisi Yönetiminde Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/anafilaksi-ve-ilac-alerjisi-yonetiminde-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Enjeksiyon Hatası ve Siyatik Sinir Zedelenmesi: Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/enjeksiyon-hatasi-ve-siyatik-sinir-zedelenmesi-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Gebelik Takibi ve Tarama Testlerinin Atlanması: Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/gebelik-takibi-ve-tarama-testlerinin-atlanmasi-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Doğum Sonrası Kanama ve Anne Ölümü: Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/dogum-sonrasi-kanama-ve-anne-olumu-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Laboratuvar Hataları: Numune Karışması ve Yanlış Sonuç Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/laboratuvar-hatalari-numune-karismasi-ve-yanlis-sonuc-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Dolgu, Botoks ve Lazer Uygulamalarında Yetkisiz Uygulama: Malpraktis Rehberi (20', 'https://hukukcularevi.com/dolgu-botoks-ve-lazer-uygulamalarinda-yetkisiz-uygulama-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Malpraktiste Arabuluculuk: Dava Şartı ve Tutanak Tuzağı Rehberi (2026)', 'https://hukukcularevi.com/malpraktiste-arabuluculuk-dava-sarti-ve-tutanak-tuzagi-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Aile Hekimliğinde ve Birinci Basamakta Kusur: Malpraktis Rehberi (2026)', 'https://hukukcularevi.com/aile-hekimliginde-ve-birinci-basamakta-kusur-malpraktis-rehberi/'),
('Trafik ve Tazminat Hukuku', 'Aktüerya (Hesap) Bilirkişi Raporuna İtiraz Dilekçesi Örneği (2026) — HMK m. 281', 'https://hukukcularevi.com/akturya-hesap-bilirkisi-raporuna-itiraz-dilekcesi-ornegi-hmk-281/'),
('Trafik ve Tazminat Hukuku', 'Kusur Bilirkişi Raporuna İtiraz Dilekçesi Örneği (2026) — Trafik Kazası', 'https://hukukcularevi.com/kusur-bilirkisi-raporuna-itiraz-dilekcesi-ornegi-hmk-281/'),
('Trafik ve Tazminat Hukuku', 'Bedeni Zararda Tahkim Başvuru Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/bedeni-zarar-sigorta-tahkim-basvuru-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Destekten Yoksun Kalma Dava Dilekçesi Örneği — Ölümlü Trafik Kazası (2026)', 'https://hukukcularevi.com/olumlu-trafik-kazasi-destekten-yoksun-kalma-dava-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Sigortaya Başvuru Dilekçesi Örneği (KTK m. 97) — Ölümlü ve Yaralamalı (2026)', 'https://hukukcularevi.com/trafik-kazasi-sigortaya-basvuru-dilekcesi-ornegi-ktk-97/'),
('Trafik ve Tazminat Hukuku', 'Trafik Kazası Maddi ve Manevi Tazminat Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/trafik-kazasi-tazminat-dava-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Trafik Cezasına İtiraz Dilekçesi Örneği (2026) — Sulh Ceza Hâkimliği ve 15 Gün', 'https://hukukcularevi.com/trafik-cezasina-itiraz-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Sürücü Belgesine El Koymaya İtiraz Dilekçesi Örneği (2026) — KTK m.48', 'https://hukukcularevi.com/surucu-belgesine-el-koymaya-itiraz-dilekcesi-ornegi-ktk-48/'),
('Trafik ve Tazminat Hukuku', 'Kasko Hasar Reddine İtiraz ve Tahkim Başvuru Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/kasko-hasar-reddine-itiraz-basvuru-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Trafik Kazasında Taksirle Yaralama Şikâyet Dilekçesi Örneği (2026) — TCK m.89', 'https://hukukcularevi.com/trafik-kazasinda-taksirle-yaralama-sikayet-dilekcesi-ornegi-tck-89/'),
('Trafik ve Tazminat Hukuku', 'Sigorta Rücu Takibine İtiraz ve Menfi Tespit Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/sigorta-rucu-takibine-itiraz-ve-menfi-tespit-dava-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'İkinci El Ayıplı Araç Dava Dilekçesi Örneği (2026) — TBK m.227', 'https://hukukcularevi.com/ikinci-el-ayipli-arac-dava-dilekcesi-ornegi-tbk-227/'),
('Trafik ve Tazminat Hukuku', 'Otoparkta Araç Hasarı ve Hırsızlık Tazminat Dava Dilekçesi Örneği (2026) — TBK m', 'https://hukukcularevi.com/otoparkta-arac-hasari-tazminat-dava-dilekcesi-ornegi-tbk-579/'),
('Trafik ve Tazminat Hukuku', 'Güvence Hesabına Başvuru Dilekçesi Örneği (2026) — 5684 s.K. m.14', 'https://hukukcularevi.com/guvence-hesabina-basvuru-dilekcesi-ornegi-5684-14/'),
('Trafik ve Tazminat Hukuku', 'Araç Haczinin ve Yakalama Şerhinin Kaldırılması Talebi Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/arac-haczinin-ve-yakalama-serhinin-kaldirilmasi-talebi-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Yol Kusuru Nedeniyle İdareye Karşı Tazminat Dava Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/yol-kusuru-nedeniyle-idareye-karsi-tazminat-dava-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'Yediemin Otopark Ücretine İtiraz Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/yediemin-otopark-ucretine-itiraz-dilekcesi-ornegi/'),
('Trafik ve Tazminat Hukuku', 'MTV Tahakkukuna İtiraz ve Düzeltme Başvuru Dilekçesi Örneği (2026) — 197 s.K. m.', 'https://hukukcularevi.com/mtv-tahakkukuna-itiraz-ve-duzeltme-basvuru-dilekcesi-ornegi-197/'),
('Trafik ve Tazminat Hukuku', 'Plakaya Kesilen Trafik Cezasına İtiraz Dilekçesi Örneği (2026) — KTK m.116', 'https://hukukcularevi.com/plakaya-kesilen-trafik-cezasina-itiraz-dilekcesi-ornegi-ktk-116/'),
('Trafik ve Tazminat Hukuku', 'Haricen Satın Alınan Aracın Devri Dava Dilekçesi Örneği (2026) — KTK m.20', 'https://hukukcularevi.com/haricen-satin-alinan-aracin-devri-dava-dilekcesi-ornegi-ktk-20/'),
('Trafik ve Tazminat Hukuku', 'Trafik Kazasında Davaya Katılma (Müdahillik) Talebi Dilekçesi Örneği (2026) — CM', 'https://hukukcularevi.com/trafik-kazasinda-davaya-katilma-mudahillik-talebi-dilekcesi-ornegi-cmk-237/'),
('Trafik ve Tazminat Hukuku', 'Trafik Kazasında Delil Tespiti Talebi Dilekçesi Örneği (2026) — HMK m.400', 'https://hukukcularevi.com/trafik-kazasinda-delil-tespiti-talebi-dilekcesi-ornegi-hmk-400/'),
('Trafik ve Tazminat Hukuku', 'HAGB Kararına Karşı İstinaf Dilekçesi Örneği (2026) — Katılan Açısından', 'https://hukukcularevi.com/hagb-kararina-karsi-istinaf-dilekcesi-ornegi-katilan-cmk-231/'),
('Trafik ve Tazminat Hukuku', 'Trafik Kazasından Sonra Hangi Dilekçe, Ne Zaman? Yol Haritası (2026)', 'https://hukukcularevi.com/trafik-kazasi-sonrasi-dilekce-yol-haritasi/'),
('Ticaret ve Şirketler Hukuku', 'SPK Savunma Dilekçesi Örneği (2026) — İdari Para Cezası Öncesi Otuz Günlük Savun', 'https://hukukcularevi.com/spk-savunma-dilekcesi-ornegi-idari-para-cezasi-oncesi-otuz-gun-spkn-105-1-sirket-yonetici-gercek-kisi-zamanasimi-menfaat-hesabi/'),
('Ticaret ve Şirketler Hukuku', 'Genel Kurul Kararının İptali Dava Dilekçesi Örneği (2026) — TTK m.445 ve 3 Ay', 'https://hukukcularevi.com/genel-kurul-kararinin-iptali-dava-dilekcesi-ornegi/'),
('Ticaret ve Şirketler Hukuku', 'Haksız Rekabet Dava Dilekçesi Örneği (2026) — TTK m.56 ve 1 Yıl / 3 Yıl', 'https://hukukcularevi.com/haksiz-rekabet-dava-dilekcesi-ornegi/'),
('Ticaret ve Şirketler Hukuku', 'Haklı Sebeple Şirketin Feshi Dava Dilekçesi Örneği (2026) — TTK m.531 ve m.636', 'https://hukukcularevi.com/hakli-sebeple-sirketin-feshi-dava-dilekcesi-ornegi-ttk-531/'),
('Sigorta Hukuku', 'Sigorta Tahkim Komisyonu Başvuru Dilekçesi Örneği (2026) — 5684 m.30', 'https://hukukcularevi.com/sigorta-tahkim-komisyonu-basvuru-dilekcesi-ornegi/'),
('Sigorta Hukuku', 'Araç Değer Kaybı Dava Dilekçesi Örneği (2026) — Sigortaya Başvuru ve 2 Yıl', 'https://hukukcularevi.com/arac-deger-kaybi-dava-dilekcesi-ornegi/'),
('Sigorta Hukuku', 'DASK Eksik Ödeme İtirazı ve Bakiye Tazminat Başvuru Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/dask-eksik-odeme-itiraz-ve-bakiye-tazminat-basvuru-dilekcesi-ornegi/'),
('Yabancılar Hukuku', 'Sınır Dışı (Deport) Kararına İtiraz Dilekçesi Örneği (2026) — 6458 m.53 ve 7 Gün', 'https://hukukcularevi.com/sinir-disi-karari-iptal-dava-dilekcesi-ornegi/'),
('Yabancılar Hukuku', 'Vatandaşlık Reddine İptal Dava Dilekçesi Örneği (2026) — 5901 ve 60 Gün', 'https://hukukcularevi.com/vatandaslik-basvurusu-reddi-iptal-dava-dilekcesi-ornegi-5901/'),
('Yabancılar Hukuku', 'Çalışma İzni Reddine İtiraz ve İptal Dava Dilekçesi Örneği (2026) — 6735 s.K. m.', 'https://hukukcularevi.com/calisma-izni-reddine-itiraz-ve-iptal-dava-dilekcesi-ornegi-6735-21/'),
('Kamu İhale Hukuku', 'İtirazen Şikâyet Başvuru Dilekçesi Örneği (2026) — 4734 m.55-56 ve 10 Gün', 'https://hukukcularevi.com/itirazen-sikayet-basvuru-dilekcesi-ornegi-kik/'),
('Kamu İhale Hukuku', 'İhale Yasaklama Kararının İptali Dava Dilekçesi Örneği (2026) — 4734 s.K. m.58', 'https://hukukcularevi.com/ihale-yasaklama-kararinin-iptali-dava-dilekcesi-ornegi-4734-58/'),
('Yargılama Usulü ve Geçici Korumalar', 'İhtiyati Tedbir Talebi Dilekçesi Örneği (2026) — HMK m.389 ve 1 Hafta / 2 Hafta', 'https://hukukcularevi.com/ihtiyati-tedbir-talebi-dilekcesi-ornegi-hmk-389/'),
('Yargılama Usulü ve Geçici Korumalar', 'Yargılamanın İadesi Dava Dilekçesi Örneği (2026) — HMK m.375 ve 3 Ay', 'https://hukukcularevi.com/yargilamanin-iadesi-dava-dilekcesi-ornegi-hmk-375/'),
('Bilişim ve Kişisel Veriler', 'Erişimin Engellenmesi Başvuru Dilekçesi Örneği (2026) — 5651 m.9 ve 24 Saat', 'https://hukukcularevi.com/erisimin-engellenmesi-basvuru-dilekcesi-ornegi-5651/'),
('Bilişim ve Kişisel Veriler', 'KVKK Başvuru ve Kurula Şikâyet Dilekçesi Örneği (2026) — 6698 s.K. m.13-14', 'https://hukukcularevi.com/kvkk-veri-sorumlusuna-basvuru-ve-kurula-sikayet-dilekcesi-ornegi-6698/'),
('Spor Hukuku', 'Spor Tahkim Kuruluna Başvuru Dilekçesi Örneği (2026) — 7 Gün / 10 Gün Ayrımı', 'https://hukukcularevi.com/tahkim-kuruluna-basvuru-dilekcesi-ornegi-spor/'),
('Rekabet Hukuku', 'Rekabet İhlali Tazminat Dava Dilekçesi Örneği (2026) — 4054 m.57-58 ve Üç Kat', 'https://hukukcularevi.com/rekabet-ihlali-tazminat-dava-dilekcesi-ornegi-4054/'),
('Enerji Hukuku', 'EPDK Cezasına İptal Dava Dilekçesi Örneği (2026) — Ankara İdare Mahkemesi ve 60', 'https://hukukcularevi.com/epdk-idari-para-cezasi-iptal-dava-dilekcesi-ornegi/'),
('Enerji Hukuku', 'Kaçak Elektrik Tahakkukuna İtiraz Dilekçesi Örneği (2026)', 'https://hukukcularevi.com/kacak-elektrik-tahakkukuna-itiraz-dilekcesi-ornegi/'),
('Tahkim ve Milletlerarası Hukuk', 'Hakem Kararının İptali Dava Dilekçesi Örneği (2026) — HMK m.439 ve 1 Ay', 'https://hukukcularevi.com/hakem-kararinin-iptali-dava-dilekcesi-ornegi-hmk-439/'),
('Tazminat ve Sorumluluk', 'Malpraktis Tazminat Dava Dilekçesi Örneği (2026) — Hangi Mahkeme, Hangi Süre?', 'https://hukukcularevi.com/malpraktis-tazminat-dava-dilekcesi-ornegi/'),
('Tazminat ve Sorumluluk', 'Hasta Hakları İhlali Başvuru Dilekçesi Örneği (2026) — Hasta Hakları Kurulu', 'https://hukukcularevi.com/hasta-haklari-ihlali-basvuru-dilekcesi-ornegi-hasta-haklari-kurulu/'),
('Tazminat ve Sorumluluk', 'Hayvan Saldırısı Tazminat Dava Dilekçesi Örneği (2026) — TBK m.67', 'https://hukukcularevi.com/hayvan-saldirisi-tazminat-dava-dilekcesi-ornegi-tbk-67/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Hasta Hakları Kurulu Başvurusu: Nasıl Yapılır, Neyi Çözer, Neyi Çözmez?', 'https://hukukcularevi.com/hasta-haklari-kurulu-basvurusu-nasil-yapilir-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Hastane ve Sağlık Kuruluşu Şikâyeti: Denetim Nasıl Tetiklenir, Ne Sonuç Doğurur?', 'https://hukukcularevi.com/hastane-ve-saglik-kurulusu-sikayeti-denetim-ve-idari-yaptirim-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Hekim Hakkında Disiplin Şikâyeti: Tabip Odası, Kurum ve Sağlık Meslekleri Kurulu', 'https://hukukcularevi.com/hekim-hakkinda-disiplin-sikayeti-tabip-odasi-kurum-ve-kurul-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'SGK''nın Rücu Davası: Tedavi Giderleri Hekimden ve Kuruluştan İstenebilir mi?', 'https://hukukcularevi.com/sgk-rucu-davasi-tedavi-giderleri-ve-hekimin-sorumlulugu-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Hasta Sırrı ve Kişisel Sağlık Verileri: Mahremiyet İhlalinde Üç Ayrı Sorumluluk', 'https://hukukcularevi.com/hasta-sirri-ve-kisisel-saglik-verileri-mahremiyet-ihlali-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Tedaviyi Reddetme Hakkı: Yazılı Belge, Rızanın Sınırları ve Refakatçi', 'https://hukukcularevi.com/tedaviyi-reddetme-hakki-yazili-belge-refakatci-ve-riza-sinirlari-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Özel Hastanede İlave Ücret (Fark Ücreti): Sınırlar, Acil İstisnası ve İade Yolu', 'https://hukukcularevi.com/ozel-hastanede-ilave-ucret-fark-ucreti-sinirlar-acil-istisnasi-ve-iade-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Sağlıkta Reklam Yasağı: Hekim ve Kuruluş Neyi Paylaşabilir, Neyi Paylaşamaz?', 'https://hukukcularevi.com/saglikta-reklam-yasagi-tanitim-ve-bilgilendirme-kurallari-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Muayenehane Açmak ve Serbest Çalışmak: Hekim Nerede Çalışabilir, Nasıl Açar?', 'https://hukukcularevi.com/muayenehane-acmak-ve-hekimin-calisma-yerleri-ruhsat-ve-yaptirimlar-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'SGK Sağlık Giderini Ödemiyorsa: Kapsam, Katılım Payı ve İtiraz Yolu', 'https://hukukcularevi.com/sgk-saglik-giderini-odemiyorsa-kapsam-katilim-payi-ve-itiraz-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Koruma Amacıyla Özgürlüğün Kısıtlanması (TMK 432): Kuruma Yerleştirme ve İtiraz', 'https://hukukcularevi.com/koruma-amaciyla-ozgurlugun-kisitlanmasi-tmk-432-zorla-tedavi-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Bulaşıcı Hastalıkta Bildirim, Tecrit ve Karantina: Yükümlülükler ve Yaptırımlar', 'https://hukukcularevi.com/bulasici-hastalikta-bildirim-tecrit-ve-karantina-1593-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Klinik Araştırmalar ve Gönüllü Hakları: Rıza, Etik Kurul ve Sorumluluk', 'https://hukukcularevi.com/klinik-arastirmalar-ve-gonullu-haklari-riza-etik-kurul-ve-sorumluluk-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Kan Bağışı ve Kan Ürünleri Hukuku: Bağışçının Hakları, Ruhsat ve Sorumluluk', 'https://hukukcularevi.com/kan-bagisi-ve-kan-urunleri-hukuku-bagiscinin-haklari-ruhsat-ve-sorumluluk/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Geleneksel ve Tamamlayıcı Tıp (GETAT): Yetki, İzin ve Sorumluluk', 'https://hukukcularevi.com/geleneksel-ve-tamamlayici-tip-getat-yetki-izin-ve-sorumluluk-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Eczane Açma, Devir ve Nakil: Nüfus Kriteri, Muvazaa ve Yaptırımlar', 'https://hukukcularevi.com/eczane-acma-devir-nakil-ve-muvazaa-eczacilik-hukuku-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Organ ve Doku Nakli Hukuku: Bağış, Rıza, Ölüm Tespiti ve Etik Kurul', 'https://hukukcularevi.com/organ-ve-doku-nakli-hukuku-bagis-riza-olum-tespiti-ve-etik-kurul-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Ölü Muayenesi, Defin Ruhsatı ve Cenaze Nakli: Kim Verir, Ne Zaman Durur?', 'https://hukukcularevi.com/olu-muayenesi-defin-ruhsati-ve-cenaze-nakli-hukuki-rehber/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Evde Sağlık ve Evde Bakım Hizmetleri: Yetki, Kayıt ve Sorumluluk', 'https://hukukcularevi.com/evde-saglik-ve-evde-bakim-hizmetleri-yetki-kayit-ve-sorumluluk-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Optisyenlik Hukuku: Yetki Sınırları, Müessese Ruhsatı ve Yaptırımlar', 'https://hukukcularevi.com/optisyenlik-hukuku-yetki-sinirlari-mussese-ruhsati-ve-yaptirimlar-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Hakkımızda', 'https://hukukcularevi.com/hakkimizda/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Ticari ve Hukuki Danışmanlık', 'https://hukukcularevi.com/danismanlik/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Referanslarımız', 'https://hukukcularevi.com/referanslarimiz/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Hukuk Gündemi', 'https://hukukcularevi.com/hukuk-gundemi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'S.S.S.', 'https://hukukcularevi.com/s-s-s/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'İletişim', 'https://hukukcularevi.com/iletisim/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Aile ve Boşanma Hukuku Rehberi', 'https://hukukcularevi.com/aile-ve-bosanma-hukuku-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'İcra ve İflas Hukuku Rehberi', 'https://hukukcularevi.com/icra-ve-iflas-hukuku-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Miras Hukuku Rehberi', 'https://hukukcularevi.com/miras-hukuku-rehberi/'),
('Sağlık Hukuku ve Malpraktis (20 rehber — 60 dilekçe örneği)', 'Kamu İhale Hukuku Rehberi', 'https://hukukcularevi.com/kamu-ihale-hukuku/');
